/**
 * Shared fr/en/ar copy for the self-service Progress product, following the
 * app's existing no-i18n-library convention of inline dictionaries.
 * French is the default language (matching the rest of Jonas Fitness); the
 * dictionaries are complete for fr, en and ar.
 */

type Lang = "fr" | "en" | "ar";

export const progressLocales: { code: Lang; label: string }[] = [
  { code: "fr", label: "FR" },
  { code: "en", label: "EN" },
  { code: "ar", label: "AR" },
];

export const progressLocale = (lang: Lang): string => lang === "fr" ? "fr-FR" : lang === "ar" ? "ar-SA" : "en-GB";

export type ProgressText = { [K in keyof typeof text.en]: string };

const text = {
  en: {
    brand: "JONAS PROGRESS · PROGRESS",
    navDashboard: "Dashboard",
    navRoutines: "Routines",
    navHistory: "History",
    out: "Sign out",
    today: "Today",
    // Layout hello
    kicker: "PROGRESS L O G",
    // Dashboard
    dashboardTitle: "Are you progressing?",
    dashboardIntro: "The numbers from your own logbook; no guesses, no scores.",
    lastSession: "Last session",
    never: "Never",
    workoutsCompleted: "WORKOUTS COMPLETED",
    workoutsCompletedHint: "all time",
    consistency: "CONSISTENCY · 4 WEEKS",
    consistencyHint: "sessions in the last 4 weeks",
    noneYet: "None yet",
    exercisesImproving: "EXERCISES TRENDING UP",
    exercisesTracked: "EXERCISES TRACKED",
    recentPRs: "RECENT PERSONAL BESTS",
    pr: "best",
    recentTrends: "Continue where you left off",
    recentTrendsHint: "Your latest logged lifts, per exercise.",
    viewAll: "View all",
    start: "Start",
    open: "Open",
    noActiveWorkout: "No active workout.",
    resume: "Resume",
    discard: "Discard",
    dashboardEmptyTitle: "Your logbook is empty.",
    dashboardEmptyHint: "Create a routine, then start a workout. Every set you log builds your baseline.",
    createRoutine: "Create a routine",
    // Routines list
    routinesTitle: "Your routines",
    routinesIntro: "The day-to-day templates you actually train.",
    newRoutine: "New routine",
    routinePlaceholder: "e.g. Push",
    add: "Add",
    noRoutines: "No routines yet.",
    noRoutinesHint: "Create your first routine to start recording training.",
    // Routine list actions (edit / delete)
    edit: "Edit",
    cancel: "Cancel",
    delete: "Delete",
    routineName: "Routine name",
    routineNameRequired: "Give the routine a name.",
    deleteRoutineTitle: "Delete routine?",
    deleteRoutineBody: "This removes the routine template. Your completed workout history will remain.",
    deleteRoutineConfirm: "Delete routine",
    // Routine sections + exercise ordering
    addSection: "Add section",
    sectionName: "Section name",
    rename: "Rename",
    deleteSection: "Delete section",
    deleteSectionBody: "Exercises stay in this routine and become ungrouped.",
    move: "Move",
    moveToSection: "Move to section",
    ungrouped: "Ungrouped",
    noExercises: "No exercises yet.",
    noExercisesHint: "Add your first exercise to build this routine.",
    // Routine detail
    routineTitle: "Routine",
    exercises: "EXERCISES",
    startWorkout: "Start workout",
    reorder: "Reorder",
    addExercise: "Add exercise",
    exerciseName: "Exercise",
    searchCatalogue: "Search the catalogue…",
    orCustom: "…or add your own",
    customExercise: "Custom exercise",
    workingSets: "SETS",
    repRange: "REP RANGE",
    targetRir: "RIR TARGET",
    unit: "UNIT",
    minLabel: "min",
    maxLabel: "max",
    remove: "Remove",
    moveUp: "Move up",
    moveDown: "Move down",
    routineNotes: "Notes",
    routinesAdvanced: "Routines that change tomorrow never rewrite what you already logged.",
    notFound: "Routine not found.",
    back: "Back",
    save: "Save",
    previousBest: "Logged before",
    // Workout logger
    themeTitle: "Workout",
    exerciseOf: "Exercise",
    of: "of",
    prev: "LAST",
    target: "TARGET",
    actual: "ACTUAL",
    weight: "WEIGHT",
    reps: "REPS",
    rir: "RIR",
    finish: "Finish workout",
    complete: "Complete",
    done: "Done",
    rest: "REST",
    pause: "Pause",
    continue: "Resume",
    reset: "Reset",
    saved: "Saved",
    saving: "Saving…",
    backToRoutines: "Back to routines",
    noPrevious: "No previous set logged.",
    lastTime: "LAST TIME",
    completedSets: "COMPLETED SETS",
    volume: "TOTAL VOLUME",
    records: "NEW PERSONAL BESTS",
    workoutComplete: "Workout complete.",
    everySetLogged: "Every set is now part of your history.",
    previousExercise: "Previous exercise",
    nextExercise: "Next exercise",
    autosave: "Autosave on",
    confirmDiscard: "Discard this in-progress workout?",
    startError: "The workout could not be started.",
    saveError: "The workout could not be saved. Reconnect and retry.",
    finishError: "The workout could not be completed.",
    activeConflict: "You already have a workout in progress. Finish or discard it first.",
    inactive: "This workout is closed.",
    notePlaceholder: "Add a session note (optional)…",
    offTarget: "Reps hit the top of your range",
    onTrack: "In range",
    underTarget: "Below target",
    // History
    historyTitle: "Exercise history",
    historyIntro: "Chronological sessions, bests and estimated 1RM trend.",
    noHistory: "No history yet.",
    noHistoryHint: "Complete a workout to build your first records.",
    load: "load",
    max: "est. 1RM",
    volumeBest: "best volume",
    setsBest: "best reps",
    sets: "sets",
    sessions: "sessions",
    session: "session",
    perExercise: "PER EXERCISE",
    allocatedBest: "BEST",
    trend: "trend",
    latest: "LATEST",
    // misc
    error: "Something went wrong.",
  },
  fr: {
    brand: "JONAS PROGRESS · PROGRESSION",
    navDashboard: "Tableau de bord",
    navRoutines: "Routines",
    navHistory: "Historique",
    out: "Déconnexion",
    today: "Aujourd'hui",
    kicker: "JOURNAL DE PROGRESSION",
    dashboardTitle: "Progressez-vous ?",
    dashboardIntro: "Les chiffres de votre propre carnet ; sans deviner, sans score.",
    lastSession: "Dernière séance",
    never: "Jamais",
    workoutsCompleted: "SÉANCES TERMINÉES",
    workoutsCompletedHint: "au total",
    consistency: "RÉGULARITÉ · 4 SEMAINES",
    consistencyHint: "séances ces 4 dernières semaines",
    noneYet: "Aucune pour l’instant",
    exercisesImproving: "EXERCICES EN HAUSSE",
    exercisesTracked: "EXERCICES SUIVIS",
    recentPRs: "MEILLEURES RÉUSSITES RÉCENTES",
    pr: "record",
    recentTrends: "Reprenez là où vous en étiez",
    recentTrendsHint: "Vos dernières levées, par exercice.",
    viewAll: "Voir tout",
    start: "Démarrer",
    open: "Ouvrir",
    noActiveWorkout: "Aucune séance en cours.",
    resume: "Reprendre",
    discard: "Abandonner",
    dashboardEmptyTitle: "Votre carnet est vide.",
    dashboardEmptyHint: "Créez une routine puis démarrez une séance. Chaque série enregistrée construit votre base.",
    createRoutine: "Créer une routine",
    routinesTitle: "Vos routines",
    routinesIntro: "Les modèles de jour que vous entraînez réellement.",
    newRoutine: "Nouvelle routine",
    routinePlaceholder: "ex. Push",
    add: "Ajouter",
    noRoutines: "Aucune routine encore.",
    noRoutinesHint: "Créez votre première routine pour commencer à enregistrer vos séances.",
    edit: "Modifier",
    cancel: "Annuler",
    delete: "Supprimer",
    routineName: "Nom de la routine",
    routineNameRequired: "Donnez un nom à la routine.",
    deleteRoutineTitle: "Supprimer cette routine ?",
    deleteRoutineBody: "Cette action supprime le modèle de la routine. Votre historique de séances terminées restera.",
    deleteRoutineConfirm: "Supprimer la routine",
    addSection: "Ajouter une section",
    sectionName: "Nom de la section",
    rename: "Renommer",
    deleteSection: "Supprimer la section",
    deleteSectionBody: "Les exercices restent dans cette routine et deviennent sans section.",
    move: "Déplacer",
    moveToSection: "Déplacer vers la section",
    ungrouped: "Sans section",
    noExercises: "Aucun exercice encore.",
    noExercisesHint: "Ajoutez votre premier exercice pour construire cette routine.",
    routineTitle: "Routine",
    exercises: "EXERCICES",
    startWorkout: "Démarrer la séance",
    reorder: "Réordonner",
    addExercise: "Ajouter un exercice",
    exerciseName: "Exercice",
    searchCatalogue: "Rechercher dans le catalogue…",
    orCustom: "…ou ajoutez le vôtre",
    customExercise: "Exercice personnalisé",
    workingSets: "SÉRIES",
    repRange: "PLAGE DE RÉP.",
    targetRir: "RIR CIBLE",
    unit: "UNITÉ",
    minLabel: "min",
    maxLabel: "max",
    remove: "Supprimer",
    moveUp: "Monter",
    moveDown: "Descendre",
    routineNotes: "Notes",
    routinesAdvanced: "Une routine qui change demain ne réécrit jamais ce que vous avez déjà enregistré.",
    notFound: "Routine introuvable.",
    back: "Retour",
    save: "Enregistrer",
    previousBest: "Déjà enregistré",
    themeTitle: "Séance",
    exerciseOf: "Exercice",
    of: "sur",
    prev: "AVANT",
    target: "CIBLE",
    actual: "REALISÉ",
    weight: "CHARGE",
    reps: "RÉP.",
    rir: "RIR",
    finish: "Terminer la séance",
    complete: "Complète",
    done: "Fait",
    rest: "REPOS",
    pause: "Pause",
    continue: "Reprendre",
    reset: "Réinitialiser",
    saved: "Enregistré",
    saving: "Enregistrement…",
    backToRoutines: "Retour aux routines",
    noPrevious: "Aucune série précédente enregistrée.",
    lastTime: "DERNIÈRE FOIS",
    completedSets: "SÉRIES TERMINÉES",
    volume: "VOLUME TOTAL",
    records: "NOUVEAUX RECORDS",
    workoutComplete: "Séance terminée.",
    everySetLogged: "Chaque série fait maintenant partie de votre historique.",
    previousExercise: "Exercice précédent",
    nextExercise: "Exercice suivant",
    autosave: "Auto-enregistrement",
    confirmDiscard: "Abandonner cette séance en cours ?",
    startError: "Impossible de démarrer la séance.",
    saveError: "Impossible d’enregistrer. Reconnectez-vous et réessayez.",
    finishError: "Impossible de terminer la séance.",
    activeConflict: "Une séance est déjà en cours. Terminez-la ou abandonnez-la d’abord.",
    inactive: "Cette séance est close.",
    notePlaceholder: "Ajouter une note de séance (facultatif)…",
    offTarget: "Toutes les séries ont atteint le haut de votre plage",
    onTrack: "Dans la plage",
    underTarget: "Sous la cible",
    historyTitle: "Historique des exercices",
    historyIntro: "Séances chronologiques, records et tendance du 1RM estimé.",
    noHistory: "Pas encore d’historique.",
    noHistoryHint: "Terminez une séance pour créer vos premiers records.",
    load: "charge",
    max: "1RM est.",
    volumeBest: "meilleur volume",
    setsBest: "record de rép.",
    sets: "séries",
    sessions: "séances",
    session: "séance",
    perExercise: "PAR EXERCICE",
    allocatedBest: "RECORD",
    trend: "tendance",
    latest: "RÉCENT",
    error: "Une erreur est survenue.",
  },
  ar: {
    brand: "JONAS PROGRESS · تقدّم",
    navDashboard: "لوحة القيادة",
    navRoutines: "الروتينات",
    navHistory: "السجل",
    out: "تسجيل الخروج",
    today: "اليوم",
    kicker: "سجل التقدم",
    dashboardTitle: "هل تتقدم؟",
    dashboardIntro: "الأرقام من سجلّك الخاص؛ بلا تخمين وبلا درجات.",
    lastSession: "آخر حصة",
    never: "أبدًا",
    workoutsCompleted: "حصص مكتملة",
    workoutsCompletedHint: "الإجمالي",
    consistency: "الاستمرارية · 4 أسابيع",
    consistencyHint: "حصص خلال آخر 4 أسابيع",
    noneYet: "لا شيء بعد",
    exercisesImproving: "تمارين في تحسّن",
    exercisesTracked: "تمارين متتبَّعة",
    recentPRs: "أفضل الأرقام الأخيرة",
    pr: "أفضل رقم",
    recentTrends: "أكمل من حيث توقفت",
    recentTrendsHint: "أحدث رفعاتك، لكل تمرين.",
    viewAll: "عرض الكل",
    start: "ابدأ",
    open: "فتح",
    noActiveWorkout: "لا حصة جارية.",
    resume: "استئناف",
    discard: "إلغاء",
    dashboardEmptyTitle: "سجلّك فارغ.",
    dashboardEmptyHint: "أنشئ روتينًا ثم ابدأ حصة. كل مجموعة تسجلّها تبني أساسك.",
    createRoutine: "إنشاء روتين",
    routinesTitle: "روتيناتك",
    routinesIntro: "القوالب اليومية التي تتدرب بها فعلاً.",
    newRoutine: "روتين جديد",
    routinePlaceholder: "مثال: دفع",
    add: "إضافة",
    noRoutines: "لا توجد روتينات بعد.",
    noRoutinesHint: "أنشئ روتينك الأول لبدء تسجيل التدريب.",
    edit: "تعديل",
    cancel: "إلغاء",
    delete: "حذف",
    routineName: "اسم الروتين",
    routineNameRequired: "أعطِ اسماً للروتين.",
    deleteRoutineTitle: "حذف هذا الروتين؟",
    deleteRoutineBody: "يحذف هذا الإجراء قالب الروتين. سيبقى سجلّ حصصك المكتملة محفوظًا.",
    deleteRoutineConfirm: "حذف الروتين",
    addSection: "إضافة قسم",
    sectionName: "اسم القسم",
    rename: "إعادة تسمية",
    deleteSection: "حذف القسم",
    deleteSectionBody: "تبقى التمارين في هذا الروتين وتصبح بدون قسم.",
    move: "نقل",
    moveToSection: "نقل إلى قسم",
    ungrouped: "بدون قسم",
    noExercises: "لا توجد تمارين بعد.",
    noExercisesHint: "أضف تمرينك الأول لبناء هذا الروتين.",
    routineTitle: "روتين",
    exercises: "تمارين",
    startWorkout: "ابدأ الحصة",
    reorder: "إعادة ترتيب",
    addExercise: "إضافة تمرين",
    exerciseName: "التمرين",
    searchCatalogue: "ابحث في الكتالوج…",
    orCustom: "...أو أضف تمرينك",
    customExercise: "تمرين مخصص",
    workingSets: "المجموعات",
    repRange: "نطاق التكرارات",
    targetRir: "RIR الهدف",
    unit: "الوحدة",
    minLabel: "الأدنى",
    maxLabel: "الأقصى",
    remove: "حذف",
    moveUp: "أعلى",
    moveDown: "أسفل",
    routineNotes: "ملاحظات",
    routinesAdvanced: "روتين يتغير غدًا لا يكتب أبدًا ما سجلتّه مسبقًا.",
    notFound: "الروتين غير موجود.",
    back: "رجوع",
    save: "حفظ",
    previousBest: "سُجّل سابقًا",
    themeTitle: "حصة",
    exerciseOf: "تمرين",
    of: "من",
    prev: "السابق",
    target: "الهدف",
    actual: "الفعلي",
    weight: "الوزن",
    reps: "التكرارات",
    rir: "RIR",
    finish: "إنهاء الحصة",
    complete: "مكتملة",
    done: "تم",
    rest: "راحة",
    pause: "إيقاف",
    continue: "استئناف",
    reset: "إعادة",
    saved: "تم الحفظ",
    saving: "جارٍ الحفظ…",
    backToRoutines: "عودة إلى الروتينات",
    noPrevious: "لم تُسجَّل مجموعة سابقة.",
    lastTime: "المرة السابقة",
    completedSets: "مجموعات مكتملة",
    volume: "الحجم الإجمالي",
    records: "أرقام شخصية جديدة",
    workoutComplete: "اكتملت الحصة.",
    everySetLogged: "كل مجموعة أصبحت الآن جزءًا من سجلك.",
    previousExercise: "التمرين السابق",
    nextExercise: "التمرين التالي",
    autosave: "حفظ تلقائي",
    confirmDiscard: "إلغاء هذه الحصة الجارية؟",
    startError: "تعذّر بدء الحصة.",
    saveError: "تعذّر حفظ الحصة. أعد الاتصال وحاول مجددًا.",
    finishError: "تعذّر إنهاء الحصة.",
    activeConflict: "لديك حصة جارية بالفعل. أنهِها أو ألغِها أولاً.",
    inactive: "هذه الحصة مغلقة.",
    notePlaceholder: "أضف ملاحظة للحصة (اختياري)…",
    offTarget: "وصلت التكرارات إلى أعلى نطاقك",
    onTrack: "ضمن النطاق",
    underTarget: "دون الهدف",
    historyTitle: "سجل التمارين",
    historyIntro: "حصص زمنية وأفضل الأرقام واتجاه 1RM التقديري.",
    noHistory: "لا يوجد سجل بعد.",
    noHistoryHint: "أكمل حصة لبناء أول الأرقام.",
    load: "الحمل",
    max: "1RM تقديري",
    volumeBest: "أفضل حجم",
    setsBest: "أفضل تكرارات",
    sets: "مجموعات",
    sessions: "حصص",
    session: "حصة",
    perExercise: "لكل تمرين",
    allocatedBest: "الأفضل",
    trend: "الاتجاه",
    latest: "الأحدث",
    error: "حدث خطأ ما.",
  },
} as const;

export function progressText(lang: Lang): ProgressText {
  return lang === "en" ? text.en : lang === "fr" ? text.fr : text.ar;
}

export function parseLang(value: string | null): Lang {
  return value === "en" || value === "ar" ? value : "fr";
}