"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { ExerciseHistoryItem } from "../lib/exercise-history";
import { exerciseDisplayName } from "../lib/exercise-catalogue";

type Lang = "fr" | "en" | "ar";
const copy = {
  fr: { kicker: "HISTORIQUE DES EXERCICES · RECORDS", title: "Voyez votre force évoluer.", intro: "Chaque série terminée alimente automatiquement votre historique.", exercise: "Exercice", load: "CHARGE MAXIMALE", max: "1RM ESTIMÉ", volume: "MEILLEUR VOLUME", reps: "MEILLEURES RÉPÉTITIONS", sessions: "SÉANCES", recent: "PERFORMANCES RÉCENTES", empty: "Terminez une séance pour créer votre premier record.", trend: "depuis la dernière séance", baseline: "Premier repère enregistré" },
  en: { kicker: "EXERCISE HISTORY · RECORDS", title: "Watch your strength move.", intro: "Every completed set builds your history automatically.", exercise: "Exercise", load: "HEAVIEST LOAD", max: "ESTIMATED 1RM", volume: "BEST VOLUME", reps: "BEST REPS", sessions: "SESSIONS", recent: "RECENT PERFORMANCE", empty: "Complete a workout to create your first record.", trend: "since the last session", baseline: "First baseline recorded" },
  ar: { kicker: "سجل التمارين · الأرقام القياسية", title: "شاهد قوتك تتطور.", intro: "كل مجموعة مكتملة تُحدّث سجلك تلقائيًا.", exercise: "التمرين", load: "أعلى وزن", max: "الحد الأقصى التقديري", volume: "أفضل حجم تدريبي", reps: "أفضل تكرارات", sessions: "الحصص", recent: "الأداء الأخير", empty: "أكمل حصة لإنشاء أول رقم قياسي.", trend: "منذ الحصة السابقة", baseline: "تم تسجيل نقطة البداية" },
} as const;
const format = (value: number, lang: Lang) => new Intl.NumberFormat(lang === "ar" ? "ar" : lang, { maximumFractionDigits: 1 }).format(value);

export default function ClientExerciseHistory({ lang, preview, clientId }: { lang: Lang; preview: boolean; clientId: number }) {
  const t = copy[lang]; const [items, setItems] = useState<ExerciseHistoryItem[]>([]); const [key, setKey] = useState("");
  const load = useCallback(async () => { const query = preview ? `?preview=${clientId}` : ""; const response = await fetch(`/api/client-exercise-history${query}`); if (!response.ok) return; const result = await response.json(); const exercises = result.exercises as ExerciseHistoryItem[]; setItems(exercises); setKey((current) => exercises.some((item) => item.key === current) ? current : exercises[0]?.key ?? ""); }, [clientId, preview]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const selected = useMemo(() => items.find((item) => item.key === key) ?? items[0], [items, key]);
  const points = selected?.points ?? []; const values = points.map((point) => point.estimatedOneRepMax); const low = Math.min(...values, 0); const high = Math.max(...values, 1); const spread = Math.max(high - low, 1); const polyline = values.map((value, index) => `${4 + (index / Math.max(1, values.length - 1)) * 92},${88 - ((value - low) / spread) * 72}`).join(" ");
  return <section className="client-exercise-history"><header><p>{t.kicker}</p><h2>{t.title}</h2><span>{t.intro}</span></header>{selected ? <><label>{t.exercise}<select value={selected.key} onChange={(event) => setKey(event.target.value)}>{items.map((item) => <option key={item.key} value={item.key}>{exerciseDisplayName(item, lang)}</option>)}</select></label><div className="client-records"><article><small>{t.load}</small><strong>{format(selected.records.heaviestWeight, lang)} kg</strong></article><article><small>{t.max}</small><strong>{format(selected.records.estimatedOneRepMax, lang)} kg</strong></article><article><small>{t.volume}</small><strong>{format(selected.records.bestSessionVolume, lang)} kg</strong></article><article><small>{t.reps}</small><strong>{selected.records.bestReps}</strong></article></div><div className="client-history-main"><article className="client-history-chart"><div><strong>{exerciseDisplayName(selected, lang)}</strong><span>{selected.sessions} {t.sessions}</span></div>{points.length > 1 ? <svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={t.title}><path d="M4 16H96M4 52H96M4 88H96" className="history-grid"/><polyline points={polyline} fill="none" vectorEffect="non-scaling-stroke"/></svg> : <p>{t.baseline}</p>}<b>{selected.trend.estimatedOneRepMax > 0 ? "+" : ""}{format(selected.trend.estimatedOneRepMax, lang)} kg <small>{t.trend}</small></b></article><article className="client-history-recent"><small>{t.recent}</small>{points.toReversed().slice(0, 5).map((point) => <div key={point.workoutId}><span><b>{new Date(point.date).toLocaleDateString(lang)}</b><small>{point.workoutTitle}</small></span><strong>{format(point.bestSet.weight, lang)} kg × {point.bestSet.reps}</strong></div>)}</article></div></> : <p className="portal-empty">{t.empty}</p>}</section>;
}
