"use client";

import { FormEvent, useEffect, useState } from "react";

type Lang = "fr" | "en" | "ar";
type Intake = { preferredLanguage: Lang; trainingExperience: string; availability: string; equipment: string; goalsDetail: string; trainingConsiderations: string; consentAt: string; updatedAt: string };

const copy = {
  fr: { kicker: "BIENVENUE", title: "Préparons votre coaching.", text: "Partagez quelques informations pour que Jonas prépare un accompagnement adapté à votre rythme.", start: "Commencer mon onboarding", review: "Votre onboarding est prêt.", edit: "Mettre à jour", formKicker: "ONBOARDING CLIENT", formTitle: "Les bases de votre accompagnement.", experience: "Votre expérience en musculation", availability: "Disponibilités et fuseau horaire", equipment: "Matériel et accès à la salle", goals: "Votre objectif et vos priorités", considerations: "Éléments importants pour l’entraînement", considerationsHint: "Facultatif · par exemple une gêne actuelle, une limitation ou une préférence importante.", consent: "Je comprends que mes réponses servent uniquement à préparer mon coaching. Je peux les mettre à jour ou demander leur suppression à mon coach.", privacy: "Ne partagez pas de diagnostic ni de document médical. En cas de douleur préoccupante, consultez un professionnel de santé.", save: "Enregistrer mon onboarding", saving: "Enregistrement…", saved: "Votre onboarding a été partagé avec Jonas.", close: "Fermer", required: "Complétez les champs obligatoires avant d’enregistrer.", options: ["Débutant", "Intermédiaire", "Confirmé", "Expérimenté"] },
  en: { kicker: "WELCOME", title: "Let’s prepare your coaching.", text: "Share a few details so Jonas can prepare coaching around your pace and real life.", start: "Start my onboarding", review: "Your onboarding is ready.", edit: "Update details", formKicker: "CLIENT ONBOARDING", formTitle: "Your coaching foundations.", experience: "Your strength-training experience", availability: "Availability and time zone", equipment: "Equipment and gym access", goals: "Your goal and priorities", considerations: "Important training considerations", considerationsHint: "Optional · for example a current discomfort, limitation or important preference.", consent: "I understand these answers are used only to prepare my coaching. I can update them or ask my coach to remove them.", privacy: "Do not share a diagnosis or medical document. For concerning pain, speak with an appropriate healthcare professional.", save: "Save my onboarding", saving: "Saving…", saved: "Your onboarding has been shared with Jonas.", close: "Close", required: "Complete the required fields before saving.", options: ["Beginner", "Intermediate", "Advanced", "Experienced"] },
  ar: { kicker: "مرحباً", title: "لنحضّر تدريبك الشخصي.", text: "شارك بعض التفاصيل ليتمكن جوناس من إعداد تدريب يناسب حياتك وإيقاعك.", start: "بدء الإعداد", review: "تم تجهيز ملف الإعداد.", edit: "تحديث المعلومات", formKicker: "إعداد العميل", formTitle: "أساسيات تدريبك.", experience: "خبرتك في تمارين القوة", availability: "أوقاتك المتاحة والمنطقة الزمنية", equipment: "المعدات وإمكانية الوصول إلى النادي", goals: "هدفك وأولوياتك", considerations: "اعتبارات مهمة للتدريب", considerationsHint: "اختياري · مثال: انزعاج حالي أو محدودية أو تفضيل مهم.", consent: "أفهم أن هذه الإجابات تُستخدم فقط لتحضير تدريبي. يمكنني تحديثها أو طلب حذفها من مدربي.", privacy: "لا تشارك تشخيصاً أو وثيقة طبية. عند وجود ألم مقلق، تواصل مع مختص صحي مناسب.", save: "حفظ الإعداد", saving: "جارٍ الحفظ…", saved: "تمت مشاركة معلومات الإعداد مع جوناس.", close: "إغلاق", required: "أكمل الحقول المطلوبة قبل الحفظ.", options: ["مبتدئ", "متوسط", "متقدم", "متمرس"] },
} as const;

export default function ClientOnboarding({ lang, preview, previewClientId }: { lang: Lang; preview: boolean; previewClientId: number }) {
  const t = copy[lang];
  const [intake, setIntake] = useState<Intake | null>(null); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  const query = preview ? "?preview=" + previewClientId : "";
  useEffect(() => { let active = true; void fetch("/api/client-onboarding" + query).then((response) => response.json().catch(() => ({})).then((data) => ({ response, data }))).then(({ response, data }) => { if (active) { if (response.ok) setIntake(data.intake ?? null); setLoading(false); } }).catch(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [query]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (preview) return; const form = new FormData(event.currentTarget); if (!form.get("consent")) { setNotice(t.required); return; } setSaving(true); setNotice(""); const response = await fetch("/api/client-onboarding", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ preferredLanguage: lang, trainingExperience: form.get("trainingExperience"), availability: form.get("availability"), equipment: form.get("equipment"), goalsDetail: form.get("goalsDetail"), trainingConsiderations: form.get("trainingConsiderations"), consent: true }) }); const data = await response.json().catch(() => ({})); if (response.ok) { setIntake(data.intake); setShowForm(false); setNotice(t.saved); } else setNotice(data.error ?? t.required); setSaving(false); }
  if (loading) return null;
  return <><section className={`client-onboarding ${intake ? "complete" : ""}`}><div><p>{t.kicker}</p><h2>{intake ? t.review : t.title}</h2><span>{intake ? `${t.experience}: ${intake.trainingExperience}` : t.text}</span></div><button className="portal-button" onClick={() => setShowForm(true)} disabled={preview}>{intake ? t.edit : t.start}<span>{lang === "ar" ? "←" : "→"}</span></button></section>{notice && <p className="portal-notice">✓ {notice}</p>}
    {showForm && <div className="modal-backdrop" role="presentation" onMouseDown={() => setShowForm(false)}><form className="portal-form onboarding-form" onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><div className="portal-form-head"><div><p>{t.formKicker}</p><h2>{t.formTitle}</h2></div><button type="button" aria-label={t.close} onClick={() => setShowForm(false)}>×</button></div><label>{t.experience}<select name="trainingExperience" defaultValue={intake?.trainingExperience ?? ""} required><option value="" disabled>—</option>{t.options.map((option) => <option key={option}>{option}</option>)}</select></label><label>{t.availability}<textarea name="availability" required defaultValue={intake?.availability ?? ""} placeholder={lang === "fr" ? "Exemple : lundi et mercredi soir, GMT+2" : lang === "ar" ? "مثال: الإثنين والأربعاء مساءً، GMT+2" : "Example: Monday and Wednesday evenings, GMT+2"} /></label><label>{t.equipment}<input name="equipment" defaultValue={intake?.equipment ?? ""} placeholder={lang === "fr" ? "Exemple : salle complète, haltères à domicile…" : lang === "ar" ? "مثال: نادٍ كامل التجهيز أو أوزان منزلية…" : "Example: full gym, home dumbbells…"} /></label><label>{t.goals}<textarea name="goalsDetail" required defaultValue={intake?.goalsDetail ?? ""} placeholder={lang === "fr" ? "Ce que vous voulez construire, améliorer ou changer." : lang === "ar" ? "ما الذي تريد بناءه أو تحسينه أو تغييره؟" : "What you want to build, improve or change."} /></label><label>{t.considerations}<textarea name="trainingConsiderations" defaultValue={intake?.trainingConsiderations ?? ""} placeholder={t.considerationsHint} /><small>{t.privacy}</small></label><label className="onboarding-consent"><input name="consent" type="checkbox" required /> <span>{t.consent}</span></label><button className="portal-button" disabled={saving || preview}>{saving ? t.saving : t.save}<span>{lang === "ar" ? "←" : "→"}</span></button></form></div>}
  </>;
}
