"use client";

import { FormEvent, useEffect, useState } from "react";

type Lang = "fr" | "en" | "ar";
type PulseSession = { clientName: string; startAt: string; durationMinutes: number; respondedAt: string | null; available: boolean; opensAt: string; expiresAt: string };
type Option = { value: number; emoji: string; text: string };
type ScaleProps = { name: string; label: string; options: Option[]; value: number; onChange: (value: number) => void };

const copy = {
  en: { pulse: "PRE-SESSION PULSE", hello: "HELLO", title: "How are you arriving today?", intro: "Five quick signals help Jonas prepare the right session for you. This takes less than 30 seconds.", energy: "Your energy right now", sleep: "How was your sleep?", soreness: "Muscle soreness", stress: "Stress level", pain: "Any pain or unusual discomfort?", noPain: "No, all good", yesPain: "Yes, tell Jonas", painArea: "Where do you feel it?", painHint: "Example: right shoulder", note: "Anything Jonas should know?", optional: "Optional", noteHint: "Soreness, stress, a win from this week…", send: "Send my Pulse", sending: "Sending to Jonas…", privacy: "Your answers are shared only with your coach for session preparation. This is not a medical assessment.", loading: "Loading your Pulse Check…", unavailable: "Link unavailable.", complete: "CHECK-IN COMPLETE", thanks: "Thanks", received: "Jonas has received your readiness update and will review it before your session.", warning: "If pain or symptoms worsen, contact an appropriate healthcare professional.", notOpen: "Not open yet.", opens: "This check-in opens 24 hours before your session on", error: "Your Pulse Check could not be sent.", empty: "Empty", low: "Low", okay: "Okay", good: "Good", ready: "Ready", poor: "Poor", light: "Light", great: "Great", none: "None", high: "High", medium: "Medium" },
  fr: { pulse: "PULSE AVANT SÉANCE", hello: "BONJOUR", title: "Comment vous sentez-vous aujourd’hui ?", intro: "Cinq signaux rapides aident Jonas à préparer la bonne séance pour vous. Cela prend moins de 30 secondes.", energy: "Votre énergie maintenant", sleep: "Comment avez-vous dormi ?", soreness: "Courbatures musculaires", stress: "Niveau de stress", pain: "Douleur ou inconfort inhabituel ?", noPain: "Non, tout va bien", yesPain: "Oui, prévenir Jonas", painArea: "Où ressentez-vous la douleur ?", painHint: "Exemple : épaule droite", note: "Autre chose à signaler à Jonas ?", optional: "Facultatif", noteHint: "Courbatures, stress, une victoire de la semaine…", send: "Envoyer mon Pulse", sending: "Envoi à Jonas…", privacy: "Vos réponses sont partagées uniquement avec votre coach pour préparer la séance. Ce n’est pas une évaluation médicale.", loading: "Chargement de votre Pulse…", unavailable: "Lien indisponible.", complete: "BILAN ENVOYÉ", thanks: "Merci", received: "Jonas a reçu votre état du jour et le consultera avant la séance.", warning: "Si une douleur ou des symptômes s’aggravent, contactez un professionnel de santé approprié.", notOpen: "Pas encore ouvert.", opens: "Ce bilan s’ouvre 24 heures avant votre séance le", error: "Votre Pulse n’a pas pu être envoyé.", empty: "Épuisé", low: "Faible", okay: "Correct", good: "Bien", ready: "Prêt", poor: "Mauvais", light: "Léger", great: "Excellent", none: "Aucune", high: "Élevées", medium: "Moyennes" },
  ar: { pulse: "تقييم ما قبل الجلسة", hello: "مرحباً", title: "كيف تشعر اليوم؟", intro: "خمسة مؤشرات سريعة تساعد جوناس على تحضير الجلسة المناسبة لك. يستغرق الأمر أقل من 30 ثانية.", energy: "طاقتك الآن", sleep: "كيف كان نومك؟", soreness: "إجهاد العضلات", stress: "مستوى التوتر", pain: "هل لديك ألم أو انزعاج غير معتاد؟", noPain: "لا، كل شيء بخير", yesPain: "نعم، أخبر جوناس", painArea: "أين تشعر بالألم؟", painHint: "مثال: الكتف الأيمن", note: "هل هناك شيء آخر يجب أن يعرفه جوناس؟", optional: "اختياري", noteHint: "إجهاد، توتر، أو إنجاز هذا الأسبوع…", send: "إرسال التقييم", sending: "جارٍ الإرسال إلى جوناس…", privacy: "تُشارك إجاباتك مع مدربك فقط لتحضير الجلسة. هذا ليس تقييماً طبياً.", loading: "جارٍ تحميل تقييمك…", unavailable: "الرابط غير متاح.", complete: "اكتمل التقييم", thanks: "شكراً", received: "تلقى جوناس تحديث جاهزيتك وسيراجعه قبل الجلسة.", warning: "إذا ازداد الألم أو الأعراض، تواصل مع مختص صحي مناسب.", notOpen: "لم يفتح بعد.", opens: "يفتح هذا التقييم قبل 24 ساعة من جلستك في", error: "تعذر إرسال التقييم.", empty: "مرهق", low: "منخفض", okay: "متوسط", good: "جيد", ready: "جاهز", poor: "سيئ", light: "خفيف", great: "ممتاز", none: "لا يوجد", high: "مرتفع", medium: "متوسط" },
} as const;

function Scale({ name, label, options, value, onChange }: ScaleProps) {
  return <fieldset className="pulse-question"><legend>{label}</legend><div className="pulse-options">{options.map((option) => <label className={value === option.value ? "selected" : ""} key={option.value}><input type="radio" name={name} value={option.value} checked={value === option.value} onChange={() => onChange(option.value)} /><span>{option.emoji}</span><b>{option.text}</b></label>)}</div></fieldset>;
}

function formatSession(value: string, language: Lang) {
  const locale = language === "fr" ? "fr-FR" : language === "ar" ? "ar" : "en-GB";
  return new Intl.DateTimeFormat(locale, { weekday: "long", day: "numeric", month: "long", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
}

export default function PulseClient({ token }: { token: string }) {
  const [language, setLanguage] = useState<Lang>("fr");
  const [session, setSession] = useState<PulseSession | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [sent, setSent] = useState(false);
  const [energy, setEnergy] = useState(3); const [sleep, setSleep] = useState(3); const [soreness, setSoreness] = useState(1); const [stress, setStress] = useState(1); const [pain, setPain] = useState(false); const [submitting, setSubmitting] = useState(false);
  const t = copy[language];
  useEffect(() => { fetch("/api/pulse?token=" + encodeURIComponent(token)).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Pulse Check unavailable"); setSession(data.session); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Pulse Check unavailable")).finally(() => setLoading(false)); }, [token]);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); setSubmitting(true); const form = new FormData(e.currentTarget); const response = await fetch("/api/pulse", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token, energy, sleep, soreness, stress, pain, painArea: form.get("painArea"), note: form.get("note") }) }); const data = await response.json().catch(() => ({})); if (response.ok) setSent(true); else setError(data.error ?? t.error); setSubmitting(false); }
  const energyOptions: Option[] = [{ value: 1, emoji: "😫", text: t.empty }, { value: 2, emoji: "😕", text: t.low }, { value: 3, emoji: "🙂", text: t.okay }, { value: 4, emoji: "💪", text: t.good }, { value: 5, emoji: "🔥", text: t.ready }];
  const sleepOptions: Option[] = [{ value: 1, emoji: "🥱", text: t.poor }, { value: 2, emoji: "😴", text: t.light }, { value: 3, emoji: "😌", text: t.okay }, { value: 4, emoji: "😊", text: t.good }, { value: 5, emoji: "✨", text: t.great }];
  const sorenessOptions: Option[] = [{ value: 1, emoji: "🟢", text: t.none }, { value: 2, emoji: "🟠", text: t.light }, { value: 3, emoji: "🔴", text: t.high }];
  const stressOptions: Option[] = [{ value: 1, emoji: "🌿", text: t.low }, { value: 2, emoji: "〰️", text: t.medium }, { value: 3, emoji: "⚡", text: t.high }];
  const languageButtons = <div className="pulse-language" aria-label="Language"><button type="button" className={language === "fr" ? "active" : ""} onClick={() => setLanguage("fr")}>FR</button><button type="button" className={language === "en" ? "active" : ""} onClick={() => setLanguage("en")}>EN</button><button type="button" className={language === "ar" ? "active" : ""} onClick={() => setLanguage("ar")}>AR</button></div>;
  if (loading) return <main className="pulse-page" dir={language === "ar" ? "rtl" : "ltr"}><section className="pulse-card pulse-state">{languageButtons}<span className="pulse-logo">JP</span><h1>{t.loading}</h1></section></main>;
  if (error && !session) return <main className="pulse-page" dir={language === "ar" ? "rtl" : "ltr"}><section className="pulse-card pulse-state">{languageButtons}<span className="pulse-logo">JP</span><p>{t.pulse}</p><h1>{t.unavailable}</h1><p>{error}</p></section></main>;
  if (!session) return null;
  if (sent || session.respondedAt) return <main className="pulse-page" dir={language === "ar" ? "rtl" : "ltr"}><section className="pulse-card pulse-state success">{languageButtons}<span className="pulse-logo">JP</span><i>✓</i><p>{t.complete}</p><h1>{t.thanks}, {session.clientName}.</h1><p>{t.received}</p><small>{t.warning}</small></section></main>;
  if (!session.available) return <main className="pulse-page" dir={language === "ar" ? "rtl" : "ltr"}><section className="pulse-card pulse-state">{languageButtons}<span className="pulse-logo">JP</span><p>{t.pulse}</p><h1>{t.notOpen}</h1><p>{t.opens} {formatSession(session.startAt, language)}.</p></section></main>;
  return <main className="pulse-page" dir={language === "ar" ? "rtl" : "ltr"}><form className="pulse-card" onSubmit={submit}><header><span className="pulse-logo">JP</span><div><p>JONAS PROGRESS · {t.pulse}</p><strong>{formatSession(session.startAt, language)} · {session.durationMinutes} min</strong></div>{languageButtons}</header><section className="pulse-intro"><small>{t.hello} {session.clientName.toUpperCase()}</small><h1>{t.title}</h1><p>{t.intro}</p></section>
    <Scale name="energy" label={t.energy} value={energy} onChange={setEnergy} options={energyOptions} />
    <Scale name="sleep" label={t.sleep} value={sleep} onChange={setSleep} options={sleepOptions} />
    <Scale name="soreness" label={t.soreness} value={soreness} onChange={setSoreness} options={sorenessOptions} />
    <Scale name="stress" label={t.stress} value={stress} onChange={setStress} options={stressOptions} />
    <fieldset className="pulse-question pain-question"><legend>{t.pain}</legend><div className="pain-toggle"><button type="button" className={!pain ? "selected" : ""} onClick={() => setPain(false)}>{t.noPain}</button><button type="button" className={pain ? "selected alert" : ""} onClick={() => setPain(true)}>{t.yesPain}</button></div>{pain && <label>{t.painArea}<input name="painArea" required placeholder={t.painHint} maxLength={120} /></label>}</fieldset>
    <label className="pulse-note">{t.note}<span>{t.optional}</span><textarea name="note" maxLength={400} placeholder={t.noteHint} /></label>
    {error && <p className="pulse-error" role="alert">{error}</p>}<button className="pulse-submit" disabled={submitting}>{submitting ? t.sending : t.send}<span>→</span></button><footer>{t.privacy}</footer>
  </form></main>;
}
