"use client";

import { FormEvent, useState } from "react";
import { attributionStorageKey, type Attribution } from "./lib/attribution";

type Lang = "fr" | "en" | "ar";
const text = {
  fr: { soon:"CANDIDATURE COACHING", ready:["Prêt à vous entraîner","avec une vraie direction ?"], readyText:"Présentez votre objectif et votre situation. Jonas étudiera personnellement votre demande.", open:"Déposer ma candidature", legal:"Deux minutes · Sans engagement · Réponse personnelle", title:"Parlons de votre objectif.", intro:"Ces informations permettent de vérifier si le coaching correspond à vos besoins.", contact:"VOS COORDONNÉES", name:"Nom complet", email:"E-mail", phone:"WhatsApp / téléphone", country:"Pays ou fuseau horaire", plan:"VOTRE PROJET", goal:"Objectif principal", experience:"Expérience d’entraînement", days:"Jours d’entraînement par semaine", format:"Format préféré", preference:"Contact préféré", message:"Que souhaitez-vous changer ou accomplir ?", messageHint:"Votre contexte, vos difficultés et ce que vous attendez d’un coach…", consent:"J’accepte que Jonas Fitness utilise ces informations uniquement pour répondre à ma demande de coaching.", send:"Envoyer ma candidature", sending:"Envoi…", success:"Candidature reçue.", successText:"Merci. Jonas examinera personnellement votre demande et vous contactera selon votre préférence.", close:"Fermer", error:"La candidature n’a pas pu être envoyée. Réessayez." },
  en: { soon:"COACHING APPLICATION", ready:["Ready to train","with real direction?"], readyText:"Tell me about your goal and situation. Jonas will personally review your application.", open:"Apply for coaching", legal:"Two minutes · No commitment · Personal response", title:"Let’s talk about your goal.", intro:"These details help determine whether the coaching is a good fit for you.", contact:"YOUR DETAILS", name:"Full name", email:"Email", phone:"WhatsApp / phone", country:"Country or time zone", plan:"YOUR PROJECT", goal:"Primary goal", experience:"Training experience", days:"Training days each week", format:"Preferred format", preference:"Preferred contact", message:"What would you like to change or achieve?", messageHint:"Your context, challenges and what you expect from a coach…", consent:"I agree that Jonas Fitness may use this information only to respond to my coaching application.", send:"Send my application", sending:"Sending…", success:"Application received.", successText:"Thank you. Jonas will personally review your application and contact you using your preferred method.", close:"Close", error:"Your application could not be sent. Please try again." },
  ar: { soon:"طلب التدريب", ready:["هل أنت مستعد للتدريب","باتجاه حقيقي؟"], readyText:"أخبرني عن هدفك ووضعك. سيراجع Jonas طلبك شخصيًا.", open:"قدّم طلب التدريب", legal:"دقيقتان · بدون التزام · رد شخصي", title:"لنتحدث عن هدفك.", intro:"تساعد هذه المعلومات على معرفة ما إذا كان التدريب مناسبًا لك.", contact:"بيانات التواصل", name:"الاسم الكامل", email:"البريد الإلكتروني", phone:"واتساب / الهاتف", country:"البلد أو المنطقة الزمنية", plan:"مشروعك", goal:"الهدف الرئيسي", experience:"خبرة التدريب", days:"أيام التدريب أسبوعيًا", format:"الصيغة المفضلة", preference:"وسيلة التواصل المفضلة", message:"ما الذي تريد تغييره أو تحقيقه؟", messageHint:"وضعك والتحديات وما تتوقعه من المدرب…", consent:"أوافق على استخدام Jonas Fitness لهذه المعلومات فقط للرد على طلب التدريب.", send:"إرسال طلبي", sending:"جارٍ الإرسال…", success:"تم استلام طلبك.", successText:"شكرًا لك. سيراجع Jonas طلبك شخصيًا ويتواصل معك بالطريقة التي اخترتها.", close:"إغلاق", error:"تعذّر إرسال الطلب. حاول مرة أخرى." },
} as const;
const choices = {
  fr: { goals:[["Build muscle","Prendre du muscle"],["Build strength","Développer la force"],["Fat loss","Perdre du gras"],["General fitness","Forme générale"],["Return to training","Reprendre l’entraînement"]], experience:[["Beginner","Débutant"],["1–2 years","1–2 ans"],["3–5 years","3–5 ans"],["6+ years","6 ans et plus"]], formats:[["Online","En ligne"],["In person","En présentiel"],["Hybrid","Hybride"]], contacts:[["WhatsApp","WhatsApp"],["Email","E-mail"],["Phone","Téléphone"]] },
  en: { goals:[["Build muscle","Build muscle"],["Build strength","Build strength"],["Fat loss","Fat loss"],["General fitness","General fitness"],["Return to training","Return to training"]], experience:[["Beginner","Beginner"],["1–2 years","1–2 years"],["3–5 years","3–5 years"],["6+ years","6+ years"]], formats:[["Online","Online"],["In person","In person"],["Hybrid","Hybrid"]], contacts:[["WhatsApp","WhatsApp"],["Email","Email"],["Phone","Phone"]] },
  ar: { goals:[["Build muscle","بناء العضلات"],["Build strength","زيادة القوة"],["Fat loss","خسارة الدهون"],["General fitness","اللياقة العامة"],["Return to training","العودة إلى التدريب"]], experience:[["Beginner","مبتدئ"],["1–2 years","1–2 سنة"],["3–5 years","3–5 سنوات"],["6+ years","6 سنوات أو أكثر"]], formats:[["Online","عن بُعد"],["In person","حضوري"],["Hybrid","هجين"]], contacts:[["WhatsApp","واتساب"],["Email","البريد الإلكتروني"],["Phone","الهاتف"]] },
} as const;

function storedAttribution(): Attribution | null {
  try { const value = localStorage.getItem(attributionStorageKey); return value ? JSON.parse(value) as Attribution : null; } catch { return null; }
}

export default function CoachingApplication({ lang }: { lang: Lang }) {
  const t = text[lang]; const options = choices[lang]; const [open, setOpen] = useState(false); const [sending, setSending] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState(""); const [startedAt, setStartedAt] = useState(() => Date.now());
  function show() { setStartedAt(Date.now()); setSuccess(false); setError(""); setOpen(true); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSending(true); setError(""); const form = new FormData(event.currentTarget);
    const payload = { ...Object.fromEntries(form), trainingDays: Number(form.get("trainingDays")), preferredLanguage: lang, consent: form.get("consent") === "on", startedAt, attribution: storedAttribution() };
    try { const response = await fetch("/api/apply", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify(payload) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error ?? t.error); setSuccess(true); }
    catch (issue) { setError(issue instanceof Error ? issue.message : t.error); }
    finally { setSending(false); }
  }
  return <><section className="early-section" id="early-access"><p className="eyebrow"><span/>{t.soon}</p><h2>{t.ready[0]}<br/><em>{t.ready[1]}</em></h2><p>{t.readyText}</p><button className="button button-light" type="button" onClick={show}>{t.open}<span>→</span></button><small>{t.legal}</small></section>
    {open ? <div className="application-backdrop" role="presentation" onMouseDown={() => setOpen(false)}><section className="application-modal" role="dialog" aria-modal="true" aria-labelledby="application-title" onMouseDown={(event) => event.stopPropagation()}><header><div><p>JONAS FITNESS · {t.soon}</p><h2 id="application-title">{success ? t.success : t.title}</h2><span>{success ? t.successText : t.intro}</span></div><button type="button" aria-label={t.close} onClick={() => setOpen(false)}>×</button></header>{success ? <div className="application-success"><i>✓</i><button type="button" className="button" onClick={() => setOpen(false)}>{t.close}<span>→</span></button></div> : <form onSubmit={submit}><input className="application-honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/><fieldset><legend>{t.contact}</legend><div className="application-grid"><label>{t.name}<input name="name" required autoComplete="name"/></label><label>{t.email}<input name="email" required type="email" autoComplete="email"/></label><label>{t.phone}<input name="phone" type="tel" autoComplete="tel"/></label><label>{t.country}<input name="country" required autoComplete="country-name" placeholder={lang === "fr" ? "France · Europe/Paris" : lang === "ar" ? "الإمارات · Asia/Dubai" : "France · Europe/Paris"}/></label></div></fieldset><fieldset><legend>{t.plan}</legend><div className="application-grid"><label>{t.goal}<select name="goal">{options.goals.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>{t.experience}<select name="experience">{options.experience.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>{t.days}<select name="trainingDays" defaultValue="3"><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option></select></label><label>{t.format}<select name="coachingFormat">{options.formats.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>{t.preference}<select name="contactPreference">{options.contacts.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div><label>{t.message}<textarea name="message" placeholder={t.messageHint}/></label></fieldset><label className="application-consent"><input type="checkbox" name="consent" required/><span>{t.consent}</span></label>{error ? <p className="application-error" role="alert">{error}</p> : null}<button className="application-submit" disabled={sending}>{sending ? t.sending : t.send}<span>→</span></button></form>}</section></div> : null}
  </>;
}
