"use client";

import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import CoachingApplication from "./CoachingApplication";

type Lang="fr"|"en"|"ar";
const copy={
fr:{nav:["Méthode","Coaching","À propos"],dash:"Mon espace",tag:"Plateforme de coaching · Toulon",headline:["Forgé sous la barre.","Guidé par les données."],lede:"Un coaching personnel qui associe plus de 16 ans de pratique de la musculation, un suivi précis, une nutrition réaliste et des décisions fiables.",join:"Accès prioritaire",explore:"Découvrir la méthode",human:"Un coaching humain, centré sur vous.",review:"Chaque recommandation reste validée par le coach.",proof:[["16+","Années de pratique"],["1:1","Attention personnelle"],["360°","Entraînement, récupération, nutrition"],["SUIVI","Des décisions fondées sur vos retours"]],method:"La méthode Jonas",methodTitle:["Sans bruit.","Juste des progrès."],methodText:"Une boucle simple qui transforme vos retours en décisions concrètes, semaine après semaine.",pillars:[["S’entraîner avec intention","Une programmation personnalisée selon votre niveau, emploi du temps et récupération."],["Mesurer l’essentiel","Force, mensurations, habitudes et retours réunis dans une vision claire."],["Ajuster sans deviner","Chaque bilan guide la suite et reste interprété par votre coach."]],system:"Le système de coaching",journey:"Tout votre parcours, au même endroit.",features:[["Programme","Un entraînement conçu pour vous"],["Bilans","Un retour hebdomadaire clair"],["Nutrition","Des conseils adaptés à votre vie"],["Votre coach","Des réponses personnelles et suivies"]],story:"DE L’EXPÉRIENCE À L’EXPERTISE",quote:"La musculation m’a appris que le meilleur plan est celui que l’on peut exécuter, mesurer et améliorer.",bio:"Plus de 16 ans de pratique personnelle de la musculation. Création d’une expérience de coaching moderne à Toulon, en parallèle du parcours de qualification professionnelle française.",soon:"OUVERTURE PROCHAINE",ready:["Prêt à vous entraîner","avec une vraie direction ?"],readyText:"Rejoignez les premières personnes informées de l’ouverture du coaching Jonas Fitness à Toulon.",legal:"Les services de coaching ouvriront après l’obtention de la qualification professionnelle requise.",contact:"Contact"},
en:{nav:["Method","Coaching","About"],dash:"My space",tag:"Coaching platform · Toulon",headline:["Built under the bar.","Driven by data."],lede:"Personal coaching that combines 16+ years of bodybuilding experience with precise tracking, practical nutrition and decisions you can trust.",join:"Join early access",explore:"Explore the method",human:"Human coaching, focused on you.",review:"Every recommendation stays coach-reviewed.",proof:[["16+","Years under the bar"],["1:1","Personal attention"],["360°","Training, recovery and nutrition"],["TRACK","Decisions built on your feedback"]],method:"The Jonas method",methodTitle:["No noise.","Just progress."],methodText:"A simple coaching loop that turns your feedback into clear decisions, week after week.",pillars:[["Train with intent","Personalised programming built around your level, schedule and recovery."],["Measure what matters","Strength, body metrics, habits and feedback become one clear picture."],["Adjust, don’t guess","Every check-in informs the next decision and is interpreted by your coach."]],system:"The coaching system",journey:"Your whole journey, in one place.",features:[["Programme","Training built for you"],["Check-ins","Clear weekly feedback"],["Nutrition","Guidance you can live with"],["Your coach","Personal answers and ongoing support"]],story:"FROM EXPERIENCE TO EXPERTISE",quote:"Bodybuilding taught me that the best plan is the one you can execute, measure and improve.",bio:"16+ years of personal bodybuilding practice. Building a modern coaching experience in Toulon while completing the official French qualification pathway.",soon:"OPENING SOON",ready:["Ready to train","with direction?"],readyText:"Join the first group to hear when Jonas Fitness coaching opens in Toulon.",legal:"Coaching services will open after completion of the required professional qualification.",contact:"Contact"},
ar:{nav:["المنهج","التدريب","عن جوناس"],dash:"مساحتي",tag:"منصة تدريب · تولون",headline:["خبرة صنعتها الأوزان.","وقرارات تقودها البيانات."],lede:"تدريب شخصي يجمع أكثر من 16 عامًا من خبرة كمال الأجسام مع متابعة دقيقة وتغذية عملية وقرارات يمكنك الوثوق بها.",join:"انضم مبكرًا",explore:"اكتشف المنهج",human:"تدريب بشري يركز عليك.",review:"كل توصية يراجعها المدرب قبل اعتمادها.",proof:[["+16","عامًا من الخبرة"],["1:1","اهتمام شخصي"],["360°","تدريب وتعافٍ وتغذية"],["متابعة","قرارات مبنية على ملاحظاتك"]],method:"منهج جوناس",methodTitle:["لا ضوضاء.","فقط تقدّم."],methodText:"حلقة تدريب بسيطة تحوّل ملاحظاتك إلى قرارات واضحة أسبوعًا بعد أسبوع.",pillars:[["تدرّب بهدف","برنامج شخصي يناسب مستواك وجدولك وقدرتك على التعافي."],["قِس ما يهم","القوة والقياسات والعادات والملاحظات في صورة واحدة واضحة."],["عدّل ولا تخمّن","كل متابعة توجّه القرار التالي ويقيّمها مدربك بنفسه."]],system:"نظام التدريب",journey:"رحلتك كاملة في مكان واحد.",features:[["البرنامج","تدريب مصمم لك"],["المتابعات","ملاحظات أسبوعية واضحة"],["التغذية","إرشاد يناسب حياتك"],["مدربك","إجابات شخصية ومتابعة مستمرة"]],story:"من الخبرة إلى الاحتراف",quote:"علّمتني كمال الأجسام أن أفضل خطة هي التي يمكنك تنفيذها وقياسها وتحسينها.",bio:"أكثر من 16 عامًا من الممارسة الشخصية لكمال الأجسام. أبني تجربة تدريب حديثة في تولون بالتوازي مع مسار التأهيل المهني الرسمي في فرنسا.",soon:"الافتتاح قريبًا",ready:["هل أنت مستعد للتدريب","باتجاه واضح؟"],readyText:"كن من أوائل من يعرفون موعد افتتاح تدريب Jonas Fitness في تولون.",legal:"ستُفتح خدمات التدريب بعد استكمال المؤهل المهني المطلوب.",contact:"تواصل"}
} as const;

export default function Home(){const[lang,setLang]=useState<Lang>("fr");const localized=copy[lang];const t={...localized,tag:lang==="fr"?"Plateforme de coaching internationale":lang==="ar"?"منصة تدريب عالمية":"Worldwide coaching platform",bio:lang==="fr"?"Plus de 16 ans de pratique personnelle de la musculation. Création d’une expérience de coaching moderne, accessible partout dans le monde, en parallèle du parcours de qualification professionnelle française.":lang==="ar"?"أكثر من 16 عامًا من الممارسة الشخصية لكمال الأجسام. أبني تجربة تدريب حديثة متاحة حول العالم بالتوازي مع مسار التأهيل المهني الرسمي في فرنسا.":"16+ years of personal bodybuilding practice. Building a modern coaching experience for clients worldwide while completing the official French qualification pathway.",readyText:lang==="fr"?"Rejoignez les premières personnes informées de l’ouverture du coaching Jonas Fitness, où que vous soyez.":lang==="ar"?"كن من أوائل من يعرفون موعد افتتاح تدريب Jonas Fitness أينما كنت.":"Join the first group to hear when Jonas Fitness coaching opens, wherever you are."};return <main dir={lang==="ar"?"rtl":"ltr"} className={lang==="ar"?"rtl-site":""}>
  <nav className="nav-shell"><Link className="brand" href="/"><span className="brand-mark">JF</span><span>JONAS FITNESS</span></Link><div className="nav-links"><a href="#method">{t.nav[0]}</a><a href="#coaching">{t.nav[1]}</a><a href="#about">{t.nav[2]}</a></div><div className="nav-end"><div className="lang-switch" aria-label="Language">{(["fr","en","ar"] as Lang[]).map(l=><button className={lang===l?"active":""} onClick={()=>setLang(l)} key={l}>{l.toUpperCase()}</button>)}</div><Link className="button button-small dashboard-link" href="/dashboard">{t.dash} <span>↗</span></Link></div></nav>
  <section className="hero"><div className="hero-copy"><p className="eyebrow"><span/>{t.tag}</p><h1>{t.headline[0]}<br/><em>{t.headline[1]}</em></h1><p className="hero-lede">{t.lede}</p><div className="hero-actions"><a className="button" href="#early-access">{t.join}<span>→</span></a><a className="text-link" href="#method">{t.explore}<span>↓</span></a></div><div className="trust-line"><div className="avatar-stack"><span>MH</span><span>SK</span><span>AM</span></div><p><strong>{t.human}</strong><br/>{t.review}</p></div></div><div className="hero-visual"><Image className="hero-training-image" src="/jonas-training-hero.png" alt="Athlete preparing a barbell in a gym" fill priority sizes="(max-width: 900px) 100vw, 53vw"/><div className="hero-image-shade"/><div className="signal-card signal-top"><span className="signal-icon">↗</span><div><small>12 WEEK STRENGTH</small><strong>+18.4%</strong></div></div><div className="performance-panel"><div className="panel-topline"><span>PERFORMANCE</span><span className="live-dot">LIVE</span></div><p className="metric-label">TRAINING CONSISTENCY</p><div className="metric-row"><strong>92</strong><span>%</span><small>EXCELLENT</small></div><div className="chart"><svg viewBox="0 0 520 190"><path className="chart-grid" d="M0 30H520 M0 80H520 M0 130H520 M0 180H520"/><path className="chart-line-shadow" d="M0 160 C45 158,72 126,110 134 S175 106,210 112 S270 55,305 74 S360 86,398 44 S458 48,520 12"/><path className="chart-line" d="M0 160 C45 158,72 126,110 134 S175 106,210 112 S270 55,305 74 S360 86,398 44 S458 48,520 12"/><circle cx="398" cy="44" r="6"/></svg></div><div className="week-row"><span>W1</span><span>W3</span><span>W6</span><span>W9</span><span>W12</span></div></div><div className="signal-card signal-bottom"><span className="signal-icon">✓</span><div><small>WEEKLY CHECK-IN</small><strong>READY TO REVIEW</strong></div></div><span className="hero-word">BUILD</span></div></section>
  <section className="proof-strip">{t.proof.map(([n,s])=><p key={s}><strong>{n}</strong><span>{s}</span></p>)}</section>
  <section className="method-section" id="method"><div className="section-heading"><p className="eyebrow dark"><span/>{t.method}</p><h2>{t.methodTitle[0]}<br/><em>{t.methodTitle[1]}</em></h2><p>{t.methodText}</p></div><div className="method-image-band"><Image src="/jonas-method-detail.png" alt={lang==="fr"?"Préparation attentive d’un entraînement":lang==="ar"?"تحضير دقيق لجلسة تدريب":"Thoughtful training preparation"} fill sizes="(max-width: 900px) 100vw, 86vw"/><span>DISCIPLINE · SYSTEM · PROGRESS</span></div><div className="pillar-grid">{t.pillars.map(([title,text],i)=><article className="pillar" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="coaching-section" id="coaching"><div><p className="eyebrow"><span/>{t.system}</p><h2>{t.journey}</h2></div><div className="feature-list">{t.features.map(([a,b])=><p key={a}><span>{a}</span><strong>{b}</strong></p>)}</div></section>
  <section className="story-section" id="about"><div className="story-layout"><div><p className="story-kicker">{t.story}</p><blockquote>“{t.quote}”</blockquote><div className="story-footer"><p><strong>Jonas</strong><span>Founder · Jonas Fitness</span></p><p>{t.bio}</p></div></div><div className="story-image"><Image src="/jonas-coaching-notes.png" alt={lang==="fr"?"Préparation d’un coaching personnalisé":lang==="ar"?"تحضير تدريب شخصي":"Personal coaching preparation"} fill sizes="(max-width: 900px) 86vw, 31vw"/><span>HUMAN-LED</span></div></div></section>
  <CoachingApplication lang={lang}/>
  <footer><Link className="brand" href="/"><span className="brand-mark">JF</span><span>JONAS FITNESS</span></Link><p>Online coaching · © 2026 Jonas Fitness</p><nav className="nav-legal"><Link href="/legal">Legal</Link><Link href="/legal/privacy">Privacy</Link><Link href="/legal/terms">Terms</Link><Link href="/legal/refunds">Refunds</Link></nav><a href="mailto:youniscode@gmail.com">{t.contact}</a></footer>
 </main>}
