"use client";

import Link from "next/link";
import { UserButton } from "@clerk/nextjs";
import { FormEvent, useEffect, useMemo, useState } from "react";
import AIResultView from "./AIResultView";
import LiveSessionMode from "./LiveSessionMode";
import ProgrammeLibrary from "./ProgrammeLibrary";
import ProgressTracker from "./ProgressTracker";
import OnboardingSummary from "./OnboardingSummary";

type Client={id:number;name:string;email:string;goal:string;sessionsPerWeek:number;currentWeight:number|null;adherence:number;nextCheckIn:string|null;status:string};
type CoachingSession={id:number;clientId:number;clientName:string;startAt:string;durationMinutes:number;status:string;pulsePath:string;readinessLevel:"pending"|"green"|"amber"|"red";readinessScore:number|null;aiSummary:string;coachAction:string;respondedAt:string|null};
const demo:Client[]=[
  {id:-1,name:"Maya H.",email:"maya@example.com",goal:"Build strength",sessionsPerWeek:4,currentWeight:64.2,adherence:94,nextCheckIn:"Today",status:"active"},
  {id:-2,name:"Samir K.",email:"samir@example.com",goal:"Fat loss",sessionsPerWeek:3,currentWeight:82.5,adherence:78,nextCheckIn:"Tomorrow",status:"active"},
  {id:-3,name:"Alex M.",email:"alex@example.com",goal:"Build muscle",sessionsPerWeek:5,currentWeight:76.8,adherence:87,nextCheckIn:"Fri",status:"active"},
];
const emptyClient:Client={id:0,name:"No client selected",email:"",goal:"—",sessionsPerWeek:0,currentWeight:null,adherence:0,nextCheckIn:null,status:"inactive"};

export default function DashboardClient({coachName}:{coachName:string}){
  const [clients,setClients]=useState<Client[]>(demo); const [demoMode,setDemoMode]=useState(true); const [showAdd,setShowAdd]=useState(false); const [showCheckIn,setShowCheckIn]=useState(false); const [showSchedule,setShowSchedule]=useState(false); const [showPortalAccess,setShowPortalAccess]=useState(false); const [showDelete,setShowDelete]=useState(false); const [showLiveSession,setShowLiveSession]=useState(false); const [selected,setSelected]=useState<Client>(demo[0]); const [clientFormError,setClientFormError]=useState(""); const [portalError,setPortalError]=useState(""); const [portalNotice,setPortalNotice]=useState(""); const [deleteError,setDeleteError]=useState(""); const [deleting,setDeleting]=useState(false);
  const [sessions,setSessions]=useState<CoachingSession[]>([]); const [sessionError,setSessionError]=useState(""); const [sessionNotice,setSessionNotice]=useState("");
  const [aiMode,setAiMode]=useState<"programme"|"nutrition"|"chat">("programme"); const [aiResult,setAiResult]=useState<unknown>(null); const [aiNotice,setAiNotice]=useState(""); const [aiProvider,setAiProvider]=useState("CHECKING LOCAL AI"); const [loading,setLoading]=useState(false);
  useEffect(()=>{fetch("/api/clients").then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(data.clients.length){setClients(data.clients);setSelected(data.clients[0]);setDemoMode(false)}}).catch(()=>{})},[]);
  useEffect(()=>{loadSessions()},[]);
  useEffect(()=>{fetch("/api/coach-ai").then(r=>r.ok?r.json():Promise.reject()).then(data=>setAiProvider(data.connected?`OLLAMA · ${data.model}`:"BUILT-IN FALLBACK")).catch(()=>setAiProvider("BUILT-IN FALLBACK"))},[]);
  const avg=useMemo(()=>clients.length?Math.round(clients.reduce((n,c)=>n+c.adherence,0)/clients.length):0,[clients]);
  const upcomingSessions=useMemo(()=>sessions.filter(session=>new Date(session.startAt).getTime()>Date.now()-6*60*60*1000).slice(0,6),[sessions]);
  async function loadSessions(){const r=await fetch("/api/sessions");if(r.ok){const data=await r.json();setSessions(data.sessions)} }
  async function addClient(e:FormEvent<HTMLFormElement>){e.preventDefault();setClientFormError("");const form=new FormData(e.currentTarget);const payload=Object.fromEntries(form);try{const r=await fetch("/api/clients",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof data.error==="string"?data.error:"The client could not be created.");const {client}=data;setClients(old=>demoMode?[client]:[client,...old]);setSelected(client);setDemoMode(false);setShowAdd(false)}catch(error){setClientFormError(error instanceof Error?error.message:"The client could not be created. Please try again.")}}
  async function runAI(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setAiResult(null);const form=new FormData(e.currentTarget);const payload={action:aiMode,goal:form.get("goal")??selected.goal,days:Number(form.get("days"))||selected.sessionsPerWeek,prompt:form.get("prompt")};const r=await fetch("/api/coach-ai",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();setAiResult(data.result);setAiNotice(data.notice??"");setAiProvider(data.provider==="ollama"?`OLLAMA · ${data.model}`:data.provider==="safety"?"SAFETY RESPONSE":"BUILT-IN FALLBACK");setLoading(false)}
  async function recordCheckIn(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const payload={...Object.fromEntries(form),clientId:selected.id};const r=await fetch("/api/check-ins",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(r.ok){const {checkIn}=await r.json();setClients(old=>old.map(c=>c.id===selected.id?{...c,adherence:checkIn.adherence,currentWeight:checkIn.weight??c.currentWeight}:c));setSelected(c=>({...c,adherence:checkIn.adherence,currentWeight:checkIn.weight??c.currentWeight}));setAiResult({reply:checkIn.aiSummary,coachReview:"Review this analysis against the client’s full history before adjusting their plan."});setAiNotice("AI-assisted check-in analysis. Coach approval required.");setAiMode("chat");setShowCheckIn(false);document.querySelector("#studio")?.scrollIntoView()}}
  async function scheduleSession(e:FormEvent<HTMLFormElement>){e.preventDefault();setSessionError("");const form=new FormData(e.currentTarget);const localStart=String(form.get("startAt")??"");const parsed=new Date(localStart);if(!Number.isFinite(parsed.getTime())){setSessionError("Choose a valid date and time.");return}const payload={clientId:Number(form.get("clientId")),startAt:parsed.toISOString(),durationMinutes:Number(form.get("durationMinutes"))};const r=await fetch("/api/sessions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok){setSessionError(data.error??"The session could not be scheduled.");return}setSessions(old=>[...old,data.session].sort((a,b)=>a.startAt.localeCompare(b.startAt)));setShowSchedule(false);setSessionNotice(`Pulse Check ready for ${data.session.clientName}`);document.querySelector("#calendar")?.scrollIntoView()}
  async function copyPulse(session:CoachingSession){const link=`${window.location.origin}${session.pulsePath}`;try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(link);else{const input=document.createElement("textarea");input.value=link;input.style.position="fixed";input.style.opacity="0";document.body.appendChild(input);input.select();document.execCommand("copy");input.remove()}setSessionNotice(`Pulse link copied for ${session.clientName}`)}catch{setSessionNotice(`Open Preview and copy the address for ${session.clientName}`)}}
  async function savePortalAccess(e:FormEvent<HTMLFormElement>){e.preventDefault();setPortalError("");setPortalNotice("");if(selected.id<1){setPortalError("Save a real client before creating portal access.");return}const form=new FormData(e.currentTarget);const r=await fetch(`/api/clients/${selected.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.get("email")})});const data=await r.json().catch(()=>({}));if(!r.ok){setPortalError(data.error??"The portal email could not be saved.");return}setClients(old=>old.map(client=>client.id===data.client.id?data.client:client));setSelected(data.client);setPortalNotice("Portal email saved. Your client can now sign up at the link below.")}
  async function copyClientPortal(){const link=`${window.location.origin}/client`;try{await navigator.clipboard.writeText(link);setPortalNotice("Client portal link copied.")}catch{setPortalNotice(`Send your client: ${link}`)}}
  async function deleteClient(e:FormEvent<HTMLFormElement>){e.preventDefault();if(selected.id<1)return;setDeleting(true);setDeleteError("");const form=new FormData(e.currentTarget);const r=await fetch(`/api/clients/${selected.id}`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmName:form.get("confirmName")})});const data=await r.json().catch(()=>({}));if(!r.ok){setDeleteError(data.error??"The client could not be deleted.");setDeleting(false);return}const remaining=clients.filter(client=>client.id!==selected.id);setClients(remaining);setSelected(remaining[0]??emptyClient);setSessions(old=>old.filter(session=>session.clientId!==selected.id));setShowDelete(false);setDeleting(false);setSessionNotice(`${data.name} and their coaching data were deleted.`)}
  function sendPulse(session:CoachingSession){const link=`${window.location.origin}${session.pulsePath}`;const when=formatSessionTime(session.startAt);const message=`Hi ${session.clientName.split(" ")[0]}, your session with Jonas is ${when}. Please complete this 30-second Pulse Check before we train: ${link}`;window.open(`https://wa.me/?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")}
  return <main className="dash-shell">{showLiveSession&&selected.id>0&&<LiveSessionMode client={selected} onClose={()=>setShowLiveSession(false)} />}
    <aside className="sidebar">
      <Link className="brand dash-brand" href="/"><span className="brand-mark">JF</span><span>JONAS FITNESS</span></Link>
      <nav className="side-nav"><a className="active" href="#overview"><i>⌂</i>Overview</a><a href="#clients"><i>◎</i>Clients</a><a href="#programmes"><i>▤</i>Programmes</a><a href="#progress"><i>◒</i>Progress</a><a href="#studio"><i>✦</i>AI Studio</a><a href="#calendar"><i>□</i>Calendar</a></nav>
      <div className="side-bottom"><span className="coach-avatar">{coachName.slice(0,2).toUpperCase()}</span><div><strong>{coachName}</strong><small>Coach workspace</small></div><UserButton /></div>
    </aside>
    <section className="dash-main" id="overview">
      <header className="dash-header"><div><p>COACH OPERATING SYSTEM</p><h1>Good afternoon, {coachName}.</h1></div><div className="header-actions"><span className="demo-tag">{demoMode?"DEMO DATA":"LIVE DATA"}</span><button className="dark-button" onClick={()=>setShowAdd(true)}>+ Add client</button></div></header>
      <div className="kpi-grid"><article><small>Active clients</small><strong>{clients.length}</strong><span>Client capacity ready</span></article><article><small>Average adherence</small><strong>{avg}%</strong><span className="positive">↗ Strong this week</span></article><article><small>Check-ins due</small><strong>{Math.min(2,clients.length)}</strong><span>Review queue</span></article><article className="lime-kpi"><small>AI actions</small><strong>4</strong><span>Tools ready</span></article></div>
      <div className="dash-grid">
        <section className="dash-card client-card" id="clients"><div className="card-title"><div><p>CLIENT ROSTER</p><h2>People you coach</h2></div><button onClick={()=>setShowAdd(true)}>Add new</button></div>
          <div className="client-table"><div className="table-head"><span>Client</span><span>Goal</span><span>Adherence</span><span>Next check-in</span></div>{clients.length===0?<p className="client-empty">No saved clients yet. Add your first client to begin.</p>:clients.map(c=><button className={selected.id===c.id?"client-row selected":"client-row"} key={c.id} onClick={()=>setSelected(c)}><span className="client-name"><i>{c.name.split(" ").map(s=>s[0]).join("")}</i><b>{c.name}<small>{c.sessionsPerWeek} sessions / week</small></b></span><span>{c.goal}</span><span><b>{c.adherence}%</b><i className="progress"><em style={{width:`${c.adherence}%`}} /></i></span><span>{c.nextCheckIn||"Not set"}<b>→</b></span></button>)}</div>
        </section>
        <aside className="dash-card focus-card"><div className="card-title"><div><p>CLIENT FOCUS</p><h2>{selected.name}</h2></div><span className="status-dot">{selected.id>0?"Active":"—"}</span></div><div className="focus-metric"><span>Current weight<strong>{selected.currentWeight?`${selected.currentWeight} kg`:"—"}</strong></span><span>Sessions<strong>{selected.id>0?`${selected.sessionsPerWeek}/wk`:"—"}</strong></span></div><div className="readiness"><p>Readiness signal <strong>{selected.id>0?(selected.adherence>=85?"Ready to progress":"Needs review"):"No client"}</strong></p><div><i style={{width:`${selected.adherence}%`}} /></div></div><button className="wide-action" disabled={selected.id<1} onClick={()=>setShowCheckIn(true)}>Record weekly check-in <span>＋</span></button><button className="wide-action secondary-action" disabled={selected.id<1} onClick={()=>{setPortalError("");setPortalNotice("");setShowPortalAccess(true)}}>Client portal access <span>↗</span></button><button className="wide-action secondary-action" disabled={selected.id<1} onClick={()=>{setAiMode("programme");document.querySelector("#studio")?.scrollIntoView()}}>Build next programme <span>→</span></button><button className="wide-action danger-action" disabled={selected.id<1} onClick={()=>{setDeleteError("");setShowDelete(true)}}>Delete client <span>×</span></button></aside>
      </div>
      {selected.id>0&&<section className="live-session-launch"><div><p>COACH LIVE MODE</p><h2>Run the workout, not the paperwork.</h2><span>Log sets, notes and previous performance from an iPad, phone or laptop.</span></div><button className="dark-button" onClick={()=>setShowLiveSession(true)}>Start live session →</button></section>}
      <ProgrammeLibrary client={selected} />
      <ProgressTracker client={selected} />
      <OnboardingSummary key={selected.id} client={selected} />
      <section className="calendar-board" id="calendar"><div className="calendar-heading"><div><p>SESSION CALENDAR</p><h2>Prepare every session.</h2><span>Schedule a client, share their private Pulse Check, then review readiness before they arrive.</span></div><div><button className="refresh-button" onClick={loadSessions}>Refresh</button><button className="dark-button" onClick={()=>{setSessionError("");setShowSchedule(true)}}>+ Schedule session</button></div></div>{sessionNotice&&<p className="calendar-notice">✓ {sessionNotice}</p>}
        <div className="session-list">{upcomingSessions.length===0?<article className="empty-session"><i>◎</i><h3>No upcoming sessions.</h3><p>Schedule your first appointment to create a client Pulse link.</p></article>:upcomingSessions.map(session=><article className={`calendar-session ${session.readinessLevel}`} key={session.id}><div className="session-date"><strong>{new Date(session.startAt).toLocaleDateString(undefined,{day:"2-digit"})}</strong><span>{new Date(session.startAt).toLocaleDateString(undefined,{month:"short"}).toUpperCase()}</span></div><div className="session-person"><small>{formatSessionTime(session.startAt)} · {session.durationMinutes} MIN</small><h3>{session.clientName}</h3><p>{session.readinessLevel==="pending"?"Waiting for the client’s Pulse Check.":session.aiSummary}</p>{session.readinessLevel!=="pending"&&<div className="coach-action"><b>COACH ACTION</b><span>{session.coachAction}</span></div>}</div><div className="session-readiness"><span className={`readiness-badge ${session.readinessLevel}`}>{session.readinessLevel==="pending"?"PULSE PENDING":`${session.readinessLevel.toUpperCase()} · ${session.readinessScore}%`}</span><div><a href={session.pulsePath} target="_blank" rel="noreferrer">Preview</a><button onClick={()=>copyPulse(session)}>Copy link</button><button className="whatsapp-button" onClick={()=>sendPulse(session)}>WhatsApp ↗</button></div></div></article>)}</div>
      </section>
      <section className="ai-studio" id="studio"><div className="studio-intro"><p>JONAS COACH AI</p><h2>Turn context into<br/><em>coach-ready drafts.</em></h2><p>Generate, analyse and explain faster. Nothing reaches a client until you review and approve it.</p><div className="ai-tabs"><button className={aiMode==="programme"?"active":""} onClick={()=>{setAiMode("programme");setAiResult(null)}}>Programme</button><button className={aiMode==="nutrition"?"active":""} onClick={()=>{setAiMode("nutrition");setAiResult(null)}}>Nutrition</button><button className={aiMode==="chat"?"active":""} onClick={()=>{setAiMode("chat");setAiResult(null)}}>Client chat</button></div></div>
        <form className="ai-workbench" onSubmit={runAI}><div className="ai-badge">✦ {aiProvider}</div>{aiMode==="programme"&&<><label>Primary goal<select name="goal" defaultValue={selected.goal}><option>Build muscle</option><option>Build strength</option><option>Fat loss</option><option>General fitness</option></select></label><label>Training days<select name="days" defaultValue={selected.sessionsPerWeek}><option>2</option><option>3</option><option>4</option><option>5</option></select></label></>}{aiMode==="nutrition"&&<p className="workbench-note">Create a practical nutrition framework built around performance, consistency and coach review.</p>}{aiMode==="chat"&&<label>Client question<textarea name="prompt" placeholder="Example: I missed two sessions. What should I do?" /></label>}<button className="generate" disabled={loading}>{loading?"Thinking…":"Generate coach draft"}<span>✦</span></button>{aiResult!==null&&<AIResultView result={aiResult} mode={aiMode} clientId={selected.id} clientName={selected.name} goal={selected.goal} sessionsPerWeek={selected.sessionsPerWeek} notice={aiNotice} />}<small>General coaching support only. Review health, injury and dietary concerns with qualified professionals.</small></form>
      </section>
    </section>
    {showAdd&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setShowAdd(false)}><form className="modal" onSubmit={addClient} onMouseDown={e=>e.stopPropagation()}><div><p>NEW CLIENT</p><button type="button" aria-label="Close" onClick={()=>setShowAdd(false)}>×</button></div><h2>Start their journey.</h2><label>Name<input name="name" required placeholder="Full name" /></label><label>Email<input name="email" type="email" placeholder="client@email.com" /></label><label>Goal<select name="goal"><option>Build muscle</option><option>Build strength</option><option>Fat loss</option><option>General fitness</option></select></label><div className="form-pair"><label>Sessions / week<input name="sessionsPerWeek" type="number" min="2" max="7" defaultValue="4" /></label><label>Weight (kg)<input name="currentWeight" type="number" step="0.1" /></label></div>{clientFormError&&<p className="form-error" role="alert">{clientFormError}</p>}<button className="generate">Create client <span>→</span></button></form></div>}
    {showCheckIn&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setShowCheckIn(false)}><form className="modal" onSubmit={recordCheckIn} onMouseDown={e=>e.stopPropagation()}><div><p>WEEKLY CHECK-IN · {selected.name}</p><button type="button" aria-label="Close" onClick={()=>setShowCheckIn(false)}>×</button></div><h2>How are they responding?</h2><div className="form-pair"><label>Weight (kg)<input name="weight" type="number" step="0.1" defaultValue={selected.currentWeight??""}/></label><label>Adherence %<input name="adherence" type="number" min="0" max="100" defaultValue={selected.adherence}/></label><label>Energy / 10<input name="energy" type="number" min="1" max="10" defaultValue="7"/></label><label>Sleep / 10<input name="sleep" type="number" min="1" max="10" defaultValue="7"/></label><label>Stress / 10<input name="stress" type="number" min="1" max="10" defaultValue="5"/></label></div><label>Coach notes<input name="notes" placeholder="Performance, soreness, context…"/></label><button className="generate">Analyse check-in <span>✦</span></button></form></div>}
    {showSchedule&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setShowSchedule(false)}><form className="modal" onSubmit={scheduleSession} onMouseDown={e=>e.stopPropagation()}><div><p>NEW COACHING SESSION</p><button type="button" aria-label="Close" onClick={()=>setShowSchedule(false)}>×</button></div><h2>Prepare their session.</h2><label>Client<select name="clientId" required defaultValue={selected.id>0?selected.id:""}><option value="" disabled>Choose a saved client</option>{clients.filter(client=>client.id>0).map(client=><option value={client.id} key={client.id}>{client.name}</option>)}</select></label><label>Date and time<input name="startAt" type="datetime-local" required defaultValue={defaultSessionTime()} /></label><label>Duration<select name="durationMinutes" defaultValue="60"><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="75">75 minutes</option><option value="90">90 minutes</option><option value="120">120 minutes</option></select></label><p className="modal-hint">The private Pulse link opens 24 hours before this session and closes 6 hours after.</p>{sessionError&&<p className="form-error" role="alert">{sessionError}</p>}<button className="generate">Schedule & create Pulse <span>→</span></button></form></div>}
    {showPortalAccess&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setShowPortalAccess(false)}><form className="modal" onSubmit={savePortalAccess} onMouseDown={e=>e.stopPropagation()}><div><p>CLIENT PORTAL · {selected.name}</p><button type="button" aria-label="Close" onClick={()=>setShowPortalAccess(false)}>×</button></div><h2>Give them secure access.</h2><label>Client sign-in email<input name="email" type="email" required defaultValue={selected.email} placeholder="client@email.com" /></label><p className="modal-hint">Your client must sign up with this exact email. They will only see their own programme, sessions and progress.</p>{portalError&&<p className="form-error" role="alert">{portalError}</p>}{portalNotice&&<p className="portal-notice">✓ {portalNotice}</p>}<button className="generate">Save portal email <span>→</span></button><button type="button" className="wide-action secondary-action" onClick={copyClientPortal}>Copy client portal link <span>⧉</span></button></form></div>}
    {showDelete&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setShowDelete(false)}><form className="modal delete-modal" onSubmit={deleteClient} onMouseDown={e=>e.stopPropagation()}><div><p>DELETE CLIENT</p><button type="button" aria-label="Close" onClick={()=>setShowDelete(false)}>×</button></div><h2>Delete {selected.name}?</h2><p className="modal-hint">This permanently deletes their programmes, sessions, Pulse responses, weekly check-ins, progress history and photos. This cannot be undone.</p><label>Type <b>{selected.name}</b> to confirm<input name="confirmName" required autoComplete="off" placeholder={selected.name} /></label>{deleteError&&<p className="form-error" role="alert">{deleteError}</p>}<button className="danger-confirm" disabled={deleting}>{deleting?"Deleting…":"Delete client permanently"}<span>×</span></button></form></div>}
  </main>
}

function formatSessionTime(value:string){return new Intl.DateTimeFormat(undefined,{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}
function defaultSessionTime(){const date=new Date(Date.now()+2*60*60*1000);date.setMinutes(Math.ceil(date.getMinutes()/15)*15,0,0);const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
