"use client";

import Link from "next/link";
import { UserButton } from "@clerk/nextjs";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import AIResultView from "./AIResultView";
import LiveSessionMode from "./LiveSessionMode";
import ProgrammeLibrary from "./ProgrammeLibrary";
import ProgressTracker from "./ProgressTracker";
import OnboardingSummary from "./OnboardingSummary";
import ClientWorkoutActivity from "./ClientWorkoutActivity";
import ProgressionEngine from "./ProgressionEngine";
import ExerciseHistory from "./ExerciseHistory";
import AcquisitionDashboard from "./AcquisitionDashboard";
import LeadPipeline from "./LeadPipeline";
import CoachCommandCenter from "./CoachCommandCenter";
import CoachNotifications from "./CoachNotifications";
import JonasCoach from "./JonasCoach";
import AdaptiveCoach from "./AdaptiveCoach";
import TrainingLoadRecovery from "./TrainingLoadRecovery";

type Client={id:number;name:string;email:string;phone:string;goal:string;sessionsPerWeek:number;currentWeight:number|null;adherence:number;nextCheckIn:string|null;status:string;acquisitionSource:string;onboarding?:{stage:string;label:string};creditBalance?:number};
type CoachingSession={id:number;clientId:number;clientName:string;startAt:string;durationMinutes:number;status:string;pulsePath:string;readinessLevel:"pending"|"green"|"amber"|"red";readinessScore:number|null;aiSummary:string;coachAction:string;respondedAt:string|null;notes?:string;attendancePending?:boolean};
type SessionHistoryItem={id:number;clientId:number;clientName:string;startAt:string;durationMinutes:number;status:string;creditEffect:number};
type CreditEntry={id:number;delta:number;reason:string;note:string;relatedSessionId:number|null;createdAt:string};
const demo:Client[]=[
  {id:-1,name:"Maya H.",email:"maya@example.com",phone:"",goal:"Build strength",sessionsPerWeek:4,currentWeight:64.2,adherence:94,nextCheckIn:"Today",status:"active",acquisitionSource:"Instagram"},
  {id:-2,name:"Samir K.",email:"samir@example.com",phone:"",goal:"Fat loss",sessionsPerWeek:3,currentWeight:82.5,adherence:78,nextCheckIn:"Tomorrow",status:"active",acquisitionSource:"Google Search"},
  {id:-3,name:"Alex M.",email:"alex@example.com",phone:"",goal:"Build muscle",sessionsPerWeek:5,currentWeight:76.8,adherence:87,nextCheckIn:"Fri",status:"active",acquisitionSource:"Referral"},
];
const emptyClient:Client={id:0,name:"No client selected",email:"",phone:"",goal:"—",sessionsPerWeek:0,currentWeight:null,adherence:0,nextCheckIn:null,status:"inactive",acquisitionSource:"Unknown"};

export default function DashboardClient({coachName}:{coachName:string}){
  const [clients,setClients]=useState<Client[]>(demo); const [demoMode,setDemoMode]=useState(true); const [showAdd,setShowAdd]=useState(false); const [showCheckIn,setShowCheckIn]=useState(false); const [showSchedule,setShowSchedule]=useState(false); const [showPortalAccess,setShowPortalAccess]=useState(false); const [showDelete,setShowDelete]=useState(false); const [showLiveSession,setShowLiveSession]=useState(false); const [selected,setSelected]=useState<Client>(demo[0]); const [clientFormError,setClientFormError]=useState(""); const [portalError,setPortalError]=useState(""); const [portalNotice,setPortalNotice]=useState(""); const [deleteError,setDeleteError]=useState(""); const [deleting,setDeleting]=useState(false);
  const [sessions,setSessions]=useState<CoachingSession[]>([]); const [history,setHistory]=useState<SessionHistoryItem[]>([]); const [sessionError,setSessionError]=useState(""); const [sessionNotice,setSessionNotice]=useState(""); const [cancellingSessionId,setCancellingSessionId]=useState<number|null>(null); const [attendingSessionId,setAttendingSessionId]=useState<number|null>(null); const [rescheduleTarget,setRescheduleTarget]=useState<CoachingSession|null>(null); const [rescheduleError,setRescheduleError]=useState(""); const [creditsTarget,setCreditsTarget]=useState<Client|null>(null); const [creditsError,setCreditsError]=useState(""); const [creditsNotice,setCreditsNotice]=useState(""); const [creditLedger,setCreditLedger]=useState<CreditEntry[]>([]);
  const [aiMode,setAiMode]=useState<"nutrition"|"chat">("chat"); const [aiResult,setAiResult]=useState<unknown>(null); const [aiNotice,setAiNotice]=useState(""); const [aiProvider,setAiProvider]=useState("CHECKING LOCAL AI"); const [loading,setLoading]=useState(false);
  const selectClientAndOpen=useCallback((clientId:number,target:string)=>{const client=clients.find(item=>item.id===clientId);if(client)setSelected(client);window.requestAnimationFrame(()=>document.querySelector(target)?.scrollIntoView({behavior:"smooth",block:"start"}))},[clients]);
  useEffect(()=>{fetch("/api/clients").then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(data.clients.length){setClients(data.clients);setSelected(data.clients[0]);setDemoMode(false)}}).catch(()=>{})},[]);
  useEffect(()=>{loadSessions()},[]);
  useEffect(()=>{fetch("/api/coach-ai").then(r=>r.ok?r.json():Promise.reject()).then(data=>setAiProvider(data.connected?`OLLAMA · ${data.model}`:"BUILT-IN FALLBACK")).catch(()=>setAiProvider("BUILT-IN FALLBACK"))},[]);
  const avg=useMemo(()=>clients.length?Math.round(clients.reduce((n,c)=>n+c.adherence,0)/clients.length):0,[clients]);
  const upcomingSessions=useMemo(()=>sessions.filter(session=>new Date(session.startAt).getTime()>Date.now()-6*60*60*1000||session.attendancePending).slice(0,8),[sessions]);
  async function loadSessions(){const r=await fetch("/api/sessions");if(r.ok){const data=await r.json();setSessions(data.sessions??[]);setHistory(data.history??[])}}
  async function recordAttendance(session:CoachingSession,status:"completed"|"no_show"|"cancelled"){if(status==="cancelled"&&!window.confirm(`Cancel the session for ${session.clientName}? Their Pulse link will stop working immediately.`))return;setAttendingSessionId(session.id);setSessionError("");setSessionNotice("");try{const r=await fetch(`/api/sessions/${session.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error??"The session could not be updated.");setSessions(old=>old.filter(item=>item.id!==session.id));setClients(current=>current.map(c=>c.id===session.clientId?{...c,creditBalance:data.creditBalance}:c));setSelected(c=>c.id===session.clientId?{...c,creditBalance:data.creditBalance}:c);const label=status==="no_show"?"No-show recorded":status==="completed"?"Session completed":"Session cancelled";setSessionNotice(`${label} for ${session.clientName}. Credit effect: ${data.creditEffect>0?`+${data.creditEffect}`:data.creditEffect}.`);loadSessions()}catch(error){setSessionError(error instanceof Error?error.message:"The session could not be updated.")}finally{setAttendingSessionId(null)}}
  async function saveReschedule(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!rescheduleTarget)return;setRescheduleError("");const form=new FormData(e.currentTarget);const localStart=String(form.get("startAt")??"");const parsed=new Date(localStart);if(!Number.isFinite(parsed.getTime())){setRescheduleError("Choose a valid date and time.");return}const payload={startAt:parsed.toISOString(),durationMinutes:Number(form.get("durationMinutes")),notes:form.get("notes")??""};const r=await fetch(`/api/sessions/${rescheduleTarget.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok){setRescheduleError(data.error??"The session could not be rescheduled.");return}setRescheduleTarget(null);setSessionNotice(`Session rescheduled for ${rescheduleTarget.clientName}.`);loadSessions()}
  async function loadCreditLedger(clientId:number){const r=await fetch(`/api/session-credits?clientId=${clientId}`);if(r.ok){const data=await r.json();setCreditLedger(data.ledger??[])} }
  async function openCredits(client:Client){setCreditsError("");setCreditsNotice("");setCreditsTarget(client);setCreditLedger([]);loadCreditLedger(client.id)}
  async function addCredits(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!creditsTarget)return;setCreditsError("");setCreditsNotice("");const form=new FormData(e.currentTarget);const delta=Number(form.get("delta"));const pack=form.get("pack")==="on";const payload={clientId:creditsTarget.id,delta,pack,note:form.get("note")??""};const r=await fetch("/api/session-credits",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok){setCreditsError(data.error??"The adjustment could not be saved.");return}setClients(current=>current.map(c=>c.id===creditsTarget.id?{...c,creditBalance:data.balance}:c));setSelected(c=>c.id===creditsTarget.id?{...c,creditBalance:data.balance}:c);setCreditsNotice(pack?`+${delta} sessions added to ${creditsTarget.name}.`:`Balance adjusted by ${delta} for ${creditsTarget.name}.`);loadCreditLedger(creditsTarget.id);(e.currentTarget as HTMLFormElement).reset()}
  async function addClient(e:FormEvent<HTMLFormElement>){e.preventDefault();setClientFormError("");const form=new FormData(e.currentTarget);const payload=Object.fromEntries(form);try{const r=await fetch("/api/clients",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof data.error==="string"?data.error:"The client could not be created.");const {client}=data;setClients(old=>demoMode?[client]:[client,...old]);setSelected(client);setDemoMode(false);setShowAdd(false);notifyClientsChanged(client.id)}catch(error){setClientFormError(error instanceof Error?error.message:"The client could not be created. Please try again.")}}
  async function runAI(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setAiResult(null);const form=new FormData(e.currentTarget);const payload={action:aiMode,prompt:form.get("prompt")};const r=await fetch("/api/coach-ai",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();setAiResult(data.result);setAiNotice(data.notice??"");setAiProvider(data.provider==="ollama"?`OLLAMA · ${data.model}`:data.provider==="safety"?"SAFETY RESPONSE":"BUILT-IN FALLBACK");setLoading(false)}
  async function recordCheckIn(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const payload={...Object.fromEntries(form),clientId:selected.id};const r=await fetch("/api/check-ins",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(r.ok){const {checkIn}=await r.json();setClients(old=>old.map(c=>c.id===selected.id?{...c,adherence:checkIn.adherence,currentWeight:checkIn.weight??c.currentWeight}:c));setSelected(c=>({...c,adherence:checkIn.adherence,currentWeight:checkIn.weight??c.currentWeight}));setAiResult({reply:checkIn.aiSummary,coachReview:"Review this analysis against the client’s full history before adjusting their plan."});setAiNotice("AI-assisted check-in analysis. Coach approval required.");setAiMode("chat");setShowCheckIn(false);document.querySelector("#studio")?.scrollIntoView()}}
  async function scheduleSession(e:FormEvent<HTMLFormElement>){e.preventDefault();setSessionError("");const form=new FormData(e.currentTarget);const localStart=String(form.get("startAt")??"");const parsed=new Date(localStart);if(!Number.isFinite(parsed.getTime())){setSessionError("Choose a valid date and time.");return}const payload={clientId:Number(form.get("clientId")),startAt:parsed.toISOString(),durationMinutes:Number(form.get("durationMinutes")),notes:form.get("notes")??""};const r=await fetch("/api/sessions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok){setSessionError(data.error??"The session could not be scheduled.");return}setSessions(old=>[...old,data.session].sort((a,b)=>a.startAt.localeCompare(b.startAt)));setClients(current=>current.map(c=>c.id===Number(form.get("clientId"))?{...c,creditBalance:data.creditBalance}:c));setSelected(c=>c.id===Number(form.get("clientId"))?{...c,creditBalance:data.creditBalance}:c);setShowSchedule(false);setSessionNotice(`Pulse Check ready for ${data.session.clientName}${data.warning?` · ${data.warning}`:""}`);document.querySelector("#calendar")?.scrollIntoView()}
  async function copyPulse(session:CoachingSession){const link=`${window.location.origin}${session.pulsePath}`;try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(link);else{const input=document.createElement("textarea");input.value=link;input.style.position="fixed";input.style.opacity="0";document.body.appendChild(input);input.select();document.execCommand("copy");input.remove()}setSessionNotice(`Pulse link copied for ${session.clientName}`)}catch{setSessionNotice(`Open Preview and copy the address for ${session.clientName}`)}}
  async function savePortalAccess(e:FormEvent<HTMLFormElement>){e.preventDefault();setPortalError("");setPortalNotice("");if(selected.id<1){setPortalError("Save a real client before creating portal access.");return}const form=new FormData(e.currentTarget);const r=await fetch(`/api/clients/${selected.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.get("email")})});const data=await r.json().catch(()=>({}));if(!r.ok){setPortalError(data.error??"The portal email could not be saved.");return}setClients(old=>old.map(client=>client.id===data.client.id?data.client:client));setSelected(data.client);setPortalNotice("Portal email saved. Your client can now sign up at the link below.")}
  async function updateClientSource(acquisitionSource:string){if(selected.id<1)return;const r=await fetch(`/api/clients/${selected.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({acquisitionSource})});const data=await r.json().catch(()=>({}));if(!r.ok)return;setClients(old=>old.map(client=>client.id===data.client.id?data.client:client));setSelected(data.client)}
  async function copyClientPortal(){const link=`${window.location.origin}/client`;try{await navigator.clipboard.writeText(link);setPortalNotice("Client portal link copied.")}catch{setPortalNotice(`Send your client: ${link}`)}}
  async function deleteClient(e:FormEvent<HTMLFormElement>){e.preventDefault();if(selected.id<1)return;setDeleting(true);setDeleteError("");const form=new FormData(e.currentTarget);const r=await fetch(`/api/clients/${selected.id}`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmName:form.get("confirmName")})});const data=await r.json().catch(()=>({}));if(!r.ok){setDeleteError(data.error??"The client could not be deleted.");setDeleting(false);return}const deletedId=selected.id;const remaining=clients.filter(client=>client.id!==deletedId);setClients(remaining);setSelected(remaining[0]??emptyClient);setSessions(old=>old.filter(session=>session.clientId!==deletedId));setShowDelete(false);setDeleting(false);setSessionNotice(`${data.name} and their coaching data were deleted.`);notifyClientsChanged(deletedId)}
  function sendPulse(session:CoachingSession){const link=`${window.location.origin}${session.pulsePath}`;const when=formatSessionTime(session.startAt);const message=`Hi ${session.clientName.split(" ")[0]}, your session with Jonas is ${when}. Please complete this 30-second Pulse Check before we train: ${link}`;window.open(`https://wa.me/?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")}
  async function cancelSession(session:CoachingSession){if(!window.confirm(`Cancel the session for ${session.clientName}? Their Pulse link will stop working immediately.`))return;setCancellingSessionId(session.id);setSessionError("");setSessionNotice("");try{const r=await fetch("/api/sessions",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId:session.id})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error??"The session could not be cancelled.");setSessions(old=>old.filter(item=>item.id!==session.id));setSessionNotice(`Session cancelled for ${session.clientName}. Their Pulse link is now inactive.`)}catch(error){setSessionError(error instanceof Error?error.message:"The session could not be cancelled.")}finally{setCancellingSessionId(null)}}
  return <main className="dash-shell">{showLiveSession&&selected.id>0&&<LiveSessionMode client={selected} onClose={()=>setShowLiveSession(false)} />}
    <aside className="sidebar">
      <Link className="brand dash-brand" href="/"><span className="brand-mark">JF</span><span>JONAS FITNESS</span></Link>
      <nav className="side-nav"><a className="active" href="#overview"><i>⌂</i>Overview</a><a href="#coach-notifications"><i>♢</i>Notifications</a><a href="#leads"><i>◇</i>Leads</a><a href="#clients"><i>◎</i>Clients</a><a href="#acquisition"><i>⌁</i>Sources</a><a href="#programmes"><i>▤</i>Programmes</a><a href="#exercise-history"><i>◫</i>Records</a><a href="#progression"><i>↗</i>Progression</a><a href="#progress"><i>◒</i>Progress</a><a href="#studio"><i>✦</i>AI Studio</a><a href="#calendar"><i>□</i>Calendar</a></nav>
      <div className="side-bottom"><span className="coach-avatar">{coachName.slice(0,2).toUpperCase()}</span><div><strong>{coachName}</strong><small>Coach workspace</small></div><UserButton /></div>
    </aside>
    <section className="dash-main" id="overview">
      <header className="dash-header"><div><p>COACH OPERATING SYSTEM</p><h1>Good afternoon, {coachName}.</h1></div><div className="header-actions"><span className="demo-tag">{demoMode?"DEMO DATA":"LIVE DATA"}</span><button className="dark-button" onClick={()=>setShowAdd(true)}>+ Add client</button></div></header>
      {!demoMode&&<CoachCommandCenter onSelectClient={selectClientAndOpen} />}
      {!demoMode&&<CoachNotifications onSelectClient={selectClientAndOpen} />}
      <div className="kpi-grid"><article><small>Active clients</small><strong>{clients.length}</strong><span>Client capacity ready</span></article><article><small>Average adherence</small><strong>{avg}%</strong><span className="positive">↗ Strong this week</span></article><article><small>Check-ins due</small><strong>{Math.min(2,clients.length)}</strong><span>Review queue</span></article><article className="lime-kpi"><small>AI actions</small><strong>4</strong><span>Tools ready</span></article></div>
      <div className="dash-grid">
        <section className="dash-card client-card" id="clients"><div className="card-title"><div><p>CLIENT ROSTER</p><h2>People you coach</h2></div><button onClick={()=>setShowAdd(true)}>Add new</button></div>
          <div className="client-table"><div className="table-head"><span>Client</span><span>Goal</span><span>Adherence</span><span>Next check-in</span></div>{clients.length===0?<p className="client-empty">No saved clients yet. Add your first client to begin.</p>:clients.map(c=><button className={selected.id===c.id?"client-row selected":"client-row"} key={c.id} onClick={()=>setSelected(c)}><span className="client-name"><i>{c.name.split(" ").map(s=>s[0]).join("")}</i><span className="client-name-main"><b>{c.name}</b>{c.onboarding && <em className="client-onboarding-badge" data-stage={c.onboarding.stage}>{c.onboarding.label}</em>}<small>{c.sessionsPerWeek} sessions / week</small></span></span><span>{c.goal}</span><span><b>{c.adherence}%</b><i className="progress"><em style={{width:`${c.adherence}%`}} /></i></span><span>{c.nextCheckIn||"Not set"}<b>→</b></span></button>)}</div>
        </section>
        <aside className="dash-card focus-card"><div className="card-title"><div><p>CLIENT FOCUS</p><h2>{selected.name}</h2></div><span className="status-dot">{selected.id>0?"Active":"—"}</span></div><div className="focus-metric"><span>Current weight<strong>{selected.currentWeight?`${selected.currentWeight} kg`:"—"}</strong></span><span>Sessions<strong>{selected.id>0?`${selected.sessionsPerWeek}/wk`:"—"}</strong></span></div><label className="focus-source">Acquisition source<select disabled={selected.id<1} value={selected.acquisitionSource} onChange={event=>void updateClientSource(event.target.value)}><option>Unknown</option><option>Instagram</option><option>TikTok</option><option>Facebook</option><option>Google Search</option><option>YouTube</option><option>WhatsApp</option><option>Referral</option><option>Website</option><option>Direct</option><option>Other</option></select></label><div className="readiness"><p>Readiness signal <strong>{selected.id>0?(selected.adherence>=85?"Ready to progress":"Needs review"):"No client"}</strong></p><div><i style={{width:`${selected.adherence}%`}} /></div></div><div className="focus-credits"><div><small>SESSION CREDITS</small><strong className={selected.id>0&&(selected.creditBalance??0)<=0?"credit-empty":""}>{selected.id>0?(selected.creditBalance??0):"—"}</strong><span>{selected.id>0?(selected.creditBalance??0)<=0?"No sessions remaining":"remaining":"No client"}</span></div><button className="wide-action secondary-action" disabled={selected.id<1} onClick={()=>void openCredits(selected)}>Add credits / adjust <span>＋</span></button></div><button className="wide-action" disabled={selected.id<1} onClick={()=>setShowCheckIn(true)}>Record weekly check-in <span>＋</span></button><button className="wide-action secondary-action" disabled={selected.id<1} onClick={()=>{setPortalError("");setPortalNotice("");setShowPortalAccess(true)}}>Client portal access <span>↗</span></button><button className="wide-action secondary-action" disabled={selected.id<1} onClick={()=>document.querySelector("#coach-studio")?.scrollIntoView()}>Build next programme with Jonas Coach <span>→</span></button><button className="wide-action danger-action" disabled={selected.id<1} onClick={()=>{setDeleteError("");setShowDelete(true)}}>Delete client <span>×</span></button></aside>
      </div>
      <AcquisitionDashboard />
      <LeadPipeline onConverted={client=>{setClients(current=>[client,...current.filter(item=>item.id!==client.id)]);setSelected(client);setDemoMode(false);notifyClientsChanged(client.id)}} />
      {selected.id>0&&<section className="live-session-launch"><div><p>COACH LIVE MODE</p><h2>Run the workout, not the paperwork.</h2><span>Log sets, notes and previous performance from an iPad, phone or laptop.</span></div><button className="dark-button" onClick={()=>setShowLiveSession(true)}>Start live session →</button></section>}
      <JonasCoach client={selected} />
      <ProgrammeLibrary client={selected} />
      <ProgressTracker client={selected} />
      <OnboardingSummary key={selected.id} client={selected} />
      <ClientWorkoutActivity client={selected} />
      <ExerciseHistory client={selected} />
      <ProgressionEngine client={selected} />
      <AdaptiveCoach client={selected} />
      <TrainingLoadRecovery client={selected} />
      <section className="calendar-board" id="calendar"><div className="calendar-heading"><div><p>SESSION CALENDAR</p><h2>Prepare every session.</h2><span>Schedule a client, share their private Pulse Check, then review readiness before they arrive.</span></div><div><button className="refresh-button" onClick={loadSessions}>Refresh</button><button className="dark-button" onClick={()=>{setSessionError("");setShowSchedule(true)}}>+ Schedule session</button></div></div>{sessionNotice&&<p className="calendar-notice">✓ {sessionNotice}</p>}{sessionError&&!showSchedule&&<p className="calendar-error" role="alert">{sessionError}</p>}
        <div className="session-list">{upcomingSessions.length===0?<article className="empty-session"><i>◎</i><h3>No upcoming sessions.</h3><p>Schedule your first appointment to create a client Pulse link.</p></article>:upcomingSessions.map(session=><article className={`calendar-session ${session.readinessLevel} ${session.attendancePending?"attendance-pending":""}`} key={session.id}><div className="session-date"><strong>{new Date(session.startAt).toLocaleDateString(undefined,{day:"2-digit"})}</strong><span>{new Date(session.startAt).toLocaleDateString(undefined,{month:"short"}).toUpperCase()}</span></div><div className="session-person"><small>{formatSessionTime(session.startAt)} · {session.durationMinutes} MIN</small><h3>{session.clientName}</h3>{session.attendancePending?<p className="attendance-pending-label">ATTENDANCE PENDING — record what happened.</p>:<><p>{session.readinessLevel==="pending"?"Waiting for the client’s Pulse Check.":session.aiSummary}</p>{session.readinessLevel!=="pending"&&<div className="coach-action"><b>COACH ACTION</b><span>{session.coachAction}</span></div>}</>}</div><div className="session-readiness">{session.attendancePending?<span className="readiness-badge pending">ATTENDANCE PENDING</span>:<span className={`readiness-badge ${session.readinessLevel}`}>{session.readinessLevel==="pending"?"PULSE PENDING":`${session.readinessLevel.toUpperCase()} · ${session.readinessScore}%`}</span>}<div>{session.attendancePending?<><button className="attendance-complete" disabled={attendingSessionId===session.id} onClick={()=>void recordAttendance(session,"completed")}>{attendingSessionId===session.id?"Saving…":"Complete ✓"}</button><button className="attendance-no-show" disabled={attendingSessionId===session.id} onClick={()=>void recordAttendance(session,"no_show")}>No-show</button></>:<><a href={session.pulsePath} target="_blank" rel="noreferrer">Preview</a><button onClick={()=>copyPulse(session)}>Copy link</button><button className="whatsapp-button" onClick={()=>sendPulse(session)}>WhatsApp ↗</button></>}<button className="reschedule-session-button" onClick={()=>{setRescheduleError("");setRescheduleTarget(session)}}>Manage</button><button className="cancel-session-button" disabled={cancellingSessionId===session.id} onClick={()=>void cancelSession(session)}>{cancellingSessionId===session.id?"Cancelling…":"Cancel"}</button></div></div></article>)}</div>
        {history.length>0&&<div className="session-history"><h4>RECENT SESSION HISTORY</h4><div className="session-history-list">{history.map(item=><article key={item.id}><span className={`history-status ${item.status}`}>{item.status.replace("_"," ")}</span><strong>{item.clientName}</strong><small>{formatSessionTime(item.startAt)} · {item.durationMinutes} min</small><em className={item.creditEffect<0?"credit-debit":""}>{item.creditEffect<0?`${item.creditEffect} credit`:"0 credit"}</em></article>)}</div></div>}
      </section>
      <section className="ai-studio" id="studio"><div className="studio-intro"><p>JONAS COACH AI</p><h2>Turn context into<br/><em>coach-ready drafts.</em></h2><p>Generate, analyse and explain faster. Nothing reaches a client until you review and approve it.</p><div className="ai-tabs"><button className={aiMode==="nutrition"?"active":""} onClick={()=>{setAiMode("nutrition");setAiResult(null)}}>Nutrition</button><button className={aiMode==="chat"?"active":""} onClick={()=>{setAiMode("chat");setAiResult(null)}}>Client chat</button></div></div>
        <form className="ai-workbench" onSubmit={runAI}><div className="ai-badge">✦ {aiProvider}</div>{aiMode==="nutrition"&&<p className="workbench-note">Create a practical nutrition framework built around performance, consistency and coach review.</p>}{aiMode==="chat"&&<label>Client question<textarea name="prompt" placeholder="Example: I missed two sessions. What should I do?" /></label>}<button className="generate" disabled={loading}>{loading?"Thinking…":"Generate coach draft"}<span>✦</span></button>{aiResult!==null&&<AIResultView result={aiResult} mode={aiMode} clientId={selected.id} clientName={selected.name} goal={selected.goal} sessionsPerWeek={selected.sessionsPerWeek} notice={aiNotice} />}<small>General coaching support only. Review health, injury and dietary concerns with qualified professionals.</small></form>
      </section>
    </section>
    {showAdd&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setShowAdd(false)}><form className="modal" onSubmit={addClient} onMouseDown={e=>e.stopPropagation()}><div><p>NEW CLIENT</p><button type="button" aria-label="Close" onClick={()=>setShowAdd(false)}>×</button></div><h2>Start their journey.</h2><label>Name<input name="name" required placeholder="Full name" /></label><label>Email<input name="email" type="email" placeholder="client@email.com" /></label><label>WhatsApp / phone<input name="phone" type="tel" placeholder="+33…" /></label><label>Goal<select name="goal"><option>Build muscle</option><option>Build strength</option><option>Fat loss</option><option>General fitness</option></select></label><label>How did they find you?<select name="acquisitionSource" defaultValue="Unknown"><option>Unknown</option><option>Instagram</option><option>TikTok</option><option>Facebook</option><option>Google Search</option><option>YouTube</option><option>WhatsApp</option><option>Referral</option><option>Website</option><option>Direct</option><option>Other</option></select></label><div className="form-pair"><label>Sessions / week<input name="sessionsPerWeek" type="number" min="2" max="7" defaultValue="4" /></label><label>Weight (kg)<input name="currentWeight" type="number" step="0.1" /></label></div>{clientFormError&&<p className="form-error" role="alert">{clientFormError}</p>}<button className="generate">Create client <span>→</span></button></form></div>}
    {showCheckIn&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setShowCheckIn(false)}><form className="modal" onSubmit={recordCheckIn} onMouseDown={e=>e.stopPropagation()}><div><p>WEEKLY CHECK-IN · {selected.name}</p><button type="button" aria-label="Close" onClick={()=>setShowCheckIn(false)}>×</button></div><h2>How are they responding?</h2><div className="form-pair"><label>Weight (kg)<input name="weight" type="number" step="0.1" defaultValue={selected.currentWeight??""}/></label><label>Adherence %<input name="adherence" type="number" min="0" max="100" defaultValue={selected.adherence}/></label><label>Energy / 10<input name="energy" type="number" min="1" max="10" defaultValue="7"/></label><label>Sleep / 10<input name="sleep" type="number" min="1" max="10" defaultValue="7"/></label><label>Stress / 10<input name="stress" type="number" min="1" max="10" defaultValue="5"/></label></div><label>Coach notes<input name="notes" placeholder="Performance, soreness, context…"/></label><button className="generate">Analyse check-in <span>✦</span></button></form></div>}
    {showSchedule&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setShowSchedule(false)}><form className="modal" onSubmit={scheduleSession} onMouseDown={e=>e.stopPropagation()}><div><p>NEW COACHING SESSION</p><button type="button" aria-label="Close" onClick={()=>setShowSchedule(false)}>×</button></div><h2>Prepare their session.</h2><label>Client<select name="clientId" required defaultValue={selected.id>0?selected.id:""}><option value="" disabled>Choose a saved client</option>{clients.filter(client=>client.id>0).map(client=><option value={client.id} key={client.id}>{client.name}</option>)}</select></label><label>Date and time<input name="startAt" type="datetime-local" required defaultValue={defaultSessionTime()} /></label><label>Duration<select name="durationMinutes" defaultValue="60"><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="75">75 minutes</option><option value="90">90 minutes</option></select></label><label>Coach notes<input name="notes" placeholder="Focus, equipment, notes for this session…" /></label>{selected.id>0&&(selected.creditBalance??0)<=0&&<p className="credit-warning" role="note">⚠ No session credits remaining for {selected.name}. You can still schedule this session.</p>}<p className="modal-hint">The private Pulse link opens 24 hours before this session and closes 6 hours after.</p>{sessionError&&<p className="form-error" role="alert">{sessionError}</p>}<button className="generate">Schedule & create Pulse <span>→</span></button></form></div>}
    {showPortalAccess&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setShowPortalAccess(false)}><form className="modal" onSubmit={savePortalAccess} onMouseDown={e=>e.stopPropagation()}><div><p>CLIENT PORTAL · {selected.name}</p><button type="button" aria-label="Close" onClick={()=>setShowPortalAccess(false)}>×</button></div><h2>Give them secure access.</h2><label>Client sign-in email<input name="email" type="email" required defaultValue={selected.email} placeholder="client@email.com" /></label><p className="modal-hint">Your client must sign up with this exact email. They will only see their own programme, sessions and progress.</p>{portalError&&<p className="form-error" role="alert">{portalError}</p>}{portalNotice&&<p className="portal-notice">✓ {portalNotice}</p>}<button className="generate">Save portal email <span>→</span></button><button type="button" className="wide-action secondary-action" onClick={copyClientPortal}>Copy client portal link <span>⧉</span></button></form></div>}
    {showDelete&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setShowDelete(false)}><form className="modal delete-modal" onSubmit={deleteClient} onMouseDown={e=>e.stopPropagation()}><div><p>DELETE CLIENT</p><button type="button" aria-label="Close" onClick={()=>setShowDelete(false)}>×</button></div><h2>Delete {selected.name}?</h2><p className="modal-hint">This permanently deletes their programmes, sessions, Pulse responses, weekly check-ins, progress history and photos. This cannot be undone.</p><label>Type <b>{selected.name}</b> to confirm<input name="confirmName" required autoComplete="off" placeholder={selected.name} /></label>{deleteError&&<p className="form-error" role="alert">{deleteError}</p>}<button className="danger-confirm" disabled={deleting}>{deleting?"Deleting…":"Delete client permanently"}<span>×</span></button></form></div>}
    {rescheduleTarget&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setRescheduleTarget(null)}><form className="modal" onSubmit={saveReschedule} onMouseDown={e=>e.stopPropagation()}><div><p>MANAGE SESSION</p><button type="button" aria-label="Close" onClick={()=>setRescheduleTarget(null)}>×</button></div><h2>{rescheduleTarget.clientName}</h2><label>Date and time<input name="startAt" type="datetime-local" required defaultValue={localInputValue(rescheduleTarget.startAt)} /></label><label>Duration<select name="durationMinutes" defaultValue={rescheduleTarget.durationMinutes}><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="75">75 minutes</option><option value="90">90 minutes</option></select></label><label>Coach notes<textarea name="notes" defaultValue={rescheduleTarget.notes??""} placeholder="Focus, equipment, notes for this session…" /></label>{rescheduleError&&<p className="form-error" role="alert">{rescheduleError}</p>}<button className="generate">Save changes <span>→</span></button></form></div>}
    {creditsTarget&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setCreditsTarget(null)}><div className="modal credits-modal" onMouseDown={e=>e.stopPropagation()}><div><p>SESSION CREDITS · {creditsTarget.name}</p><button type="button" aria-label="Close" onClick={()=>setCreditsTarget(null)}>×</button></div><h2>{creditsTarget.creditBalance??0} remaining</h2><form onSubmit={addCredits} className="credits-form"><div className="form-pair"><label>Adjustment<select name="delta" defaultValue="1"><option value="1">+1</option><option value="2">+2</option><option value="5">+5</option><option value="10">+10</option><option value="-1">-1</option></select></label><label className="credits-pack"><input name="pack" type="checkbox" /> Add as a session pack</label></div><label>Note / reason<input name="note" placeholder="e.g. 10-session pack purchased, correction, trial session…" /></label>{creditsError&&<p className="form-error" role="alert">{creditsError}</p>}{creditsNotice&&<p className="portal-notice">✓ {creditsNotice}</p>}<button className="generate">Save adjustment <span>→</span></button></form><div className="credits-ledger"><h4>RECENT ACTIVITY</h4>{creditLedger.length===0?<p className="credits-empty">No credit activity yet.</p>:creditLedger.slice(0,6).map(entry=><article key={entry.id}><b className={entry.delta<0?"credit-debit":""}>{entry.delta>0?`+${entry.delta}`:entry.delta}</b><span><strong>{entry.reason.replace(/_/g," ")}</strong><small>{new Date(entry.createdAt).toLocaleDateString(undefined,{day:"numeric",month:"short"})}{entry.note?` · ${entry.note}`:""}</small></span></article>)}</div></div></div>}
  </main>
}

// Roster-changing actions notify derived dashboard panels (e.g. Client
// Acquisition) so they refetch instead of staying on stale state until a
// manual refresh or full page reload.
function notifyClientsChanged(clientId:number){window.dispatchEvent(new CustomEvent("jonas-clients-changed",{detail:{clientId}}))}
function formatSessionTime(value:string){return new Intl.DateTimeFormat(undefined,{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}
function defaultSessionTime(){const date=new Date(Date.now()+2*60*60*1000);date.setMinutes(Math.ceil(date.getMinutes()/15)*15,0,0);const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
function localInputValue(value:string){const date=new Date(value);const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
