"use client";

import { useCallback, useDeferredValue, useEffect, useMemo, useState } from "react";

type Status = "new" | "contacted" | "qualified" | "client" | "lost";
type Lead = { id:number; name:string; email:string; phone:string; country:string; goal:string; experience:string; trainingDays:number; coachingFormat:string; contactPreference:string; preferredLanguage:string; message:string; status:Status; coachNotes:string; acquisitionSource:string; acquisitionCampaign:string; convertedClientId:number|null; createdAt:string };
type ConvertedClient = { id:number; name:string; email:string; phone:string; goal:string; sessionsPerWeek:number; currentWeight:number|null; adherence:number; nextCheckIn:string|null; status:string; acquisitionSource:string };
const columns: { status: Status; label: string }[] = [{status:"new",label:"New"},{status:"contacted",label:"Contacted"},{status:"qualified",label:"Qualified"},{status:"client",label:"Client"},{status:"lost",label:"Lost"}];

function whatsappUrl(phone: string, name: string) {
  const digits = phone.replace(/[^\d+]/g, "");
  const text = `Hi ${name.split(" ")[0]}, this is Jonas from Jonas Fitness. Thank you for your coaching application.`;
  return digits ? `https://wa.me/${digits.replace("+", "")}?text=${encodeURIComponent(text)}` : `https://wa.me/?text=${encodeURIComponent(text)}`;
}

export default function LeadPipeline({ onConverted }: { onConverted: (client: ConvertedClient) => void }) {
  const [leads, setLeads] = useState<Lead[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [query, setQuery] = useState(""); const [source, setSource] = useState("All"); const [converting, setConverting] = useState<number|null>(null);
  const deferredQuery = useDeferredValue(query.trim().toLowerCase());
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/leads"); const result = await response.json().catch(()=>({})); if(!response.ok) throw new Error(result.error ?? "Leads could not be loaded."); setLeads(result.leads); } catch(issue){setError(issue instanceof Error?issue.message:"Leads could not be loaded.");} finally{setLoading(false);} },[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
  const sources = useMemo(()=>["All",...new Set(leads.map(lead=>lead.acquisitionSource))],[leads]);
  const visible = useMemo(()=>leads.filter(lead=>(source==="All"||lead.acquisitionSource===source)&&(!deferredQuery||`${lead.name} ${lead.email} ${lead.phone} ${lead.goal}`.toLowerCase().includes(deferredQuery))),[leads,source,deferredQuery]);
  async function patchLead(id:number, updates:Record<string,unknown>){const response=await fetch(`/api/leads/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(updates)});const result=await response.json().catch(()=>({}));if(!response.ok){setError(result.error??"Lead could not be updated.");return null;}setLeads(current=>current.map(lead=>lead.id===id?result.lead:lead));return result.lead as Lead;}
  async function changeStatus(lead:Lead,status:Status){setError("");await patchLead(lead.id,{status});}
  async function saveNotes(lead:Lead,value:string){if(value===lead.coachNotes)return;const saved=await patchLead(lead.id,{coachNotes:value});if(saved)setNotice(`Notes saved for ${lead.name}.`)}
  async function convert(lead:Lead){if(!window.confirm(`Convert ${lead.name} into a client?`))return;setConverting(lead.id);setError("");try{const response=await fetch(`/api/leads/${lead.id}/convert`,{method:"POST"});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error??"Lead could not be converted.");setLeads(current=>current.map(item=>item.id===lead.id?result.lead:item));onConverted(result.client);setNotice(`${lead.name} is now a client and has been added to your roster.`);}catch(issue){setError(issue instanceof Error?issue.message:"Lead could not be converted.");}finally{setConverting(null)}}
  return <section className="lead-pipeline" id="leads"><header><div><p>LEAD CAPTURE · SALES PIPELINE</p><h2>From interest to client.</h2><span>Review every coaching application, follow up personally and convert only the right fit.</span></div><button className="refresh-button" onClick={()=>void load()}>{loading?"Loading…":"Refresh"}</button></header><div className="pipeline-summary"><article><small>NEW</small><strong>{visible.filter(lead=>lead.status==="new").length}</strong></article><article><small>QUALIFIED</small><strong>{visible.filter(lead=>lead.status==="qualified").length}</strong></article><article><small>CONVERTED</small><strong>{visible.filter(lead=>lead.status==="client").length}</strong></article><article><small>CONVERSION</small><strong>{visible.length?Math.round(visible.filter(lead=>lead.status==="client").length/visible.length*100):0}%</strong></article></div><div className="pipeline-toolbar"><label>Search<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Name, email, goal…"/></label><label>Source<select value={source} onChange={event=>setSource(event.target.value)}>{sources.map(item=><option key={item}>{item}</option>)}</select></label></div>{notice?<p className="pipeline-notice">✓ {notice}</p>:null}{error?<p className="form-error" role="alert">{error}</p>:null}
    <div className="pipeline-board">{columns.map(column=><section className={`pipeline-column ${column.status}`} key={column.status}><header><span>{column.label}</span><b>{visible.filter(lead=>lead.status===column.status).length}</b></header><div>{visible.filter(lead=>lead.status===column.status).map(lead=><details className="lead-card" key={lead.id}><summary><span><small>{lead.acquisitionSource}{lead.acquisitionCampaign?` · ${lead.acquisitionCampaign}`:""}</small><strong>{lead.name}</strong><em>{lead.goal} · {lead.country}</em></span><b>＋</b></summary><div className="lead-detail"><div className="lead-facts"><span><small>EXPERIENCE</small><b>{lead.experience||"—"}</b></span><span><small>TRAINING</small><b>{lead.trainingDays} days · {lead.coachingFormat}</b></span><span><small>CONTACT</small><b>{lead.contactPreference} · {lead.preferredLanguage.toUpperCase()}</b></span><span><small>APPLIED</small><b>{new Date(lead.createdAt).toLocaleDateString()}</b></span></div>{lead.message?<p>{lead.message}</p>:null}<div className="lead-contact"><a href={`mailto:${lead.email}?subject=${encodeURIComponent("Your Jonas Fitness coaching application")}`}>Email</a><a href={whatsappUrl(lead.phone,lead.name)} target="_blank" rel="noreferrer">WhatsApp ↗</a></div><label>Status<select value={lead.status} onChange={event=>void changeStatus(lead,event.target.value as Status)}>{columns.map(option=><option value={option.status} key={option.status}>{option.label}</option>)}</select></label><label>Coach notes<textarea defaultValue={lead.coachNotes} onBlur={event=>void saveNotes(lead,event.target.value)} placeholder="Fit, follow-up, objections, next step…"/></label>{lead.status!=="client"?<button className="convert-lead" disabled={converting===lead.id} onClick={()=>void convert(lead)}>{converting===lead.id?"Converting…":"Convert to client →"}</button>:<p className="converted-label">✓ Client created</p>}</div></details>)}{visible.every(lead=>lead.status!==column.status)?<p className="pipeline-empty">No {column.label.toLowerCase()} leads.</p>:null}</div></section>)}</div>
  </section>;
}
